static const int C4D_None;
static const int C4D_All;
static const int C4D_Background;
static const int C4D_Goal;
static const int C4D_Living;
static const int C4D_Object;
static const int C4D_Parallax;
static const int C4D_Rule;
static const int C4D_StaticBack;
static const int C4D_Structure;
static const int C4D_Vehicle;
static const int C4V_Array;
static const int C4V_Bool;
static const int C4V_C4Object;
static const int C4V_Int;
static const int C4V_Nil;
static const int C4V_PropList;
static const int C4V_String;
static const int COMD_Down;
static const int COMD_DownLeft;
static const int COMD_DownRight;
static const int COMD_Left;
static const int COMD_None;
static const int COMD_Right;
static const int COMD_Stop;
static const int COMD_Up;
static const int COMD_UpLeft;
static const int COMD_UpRight;
static const int DIR_Left;
static const int DIR_Right;
static const int NO_OWNER;
static const int OCF_Alive;
static const int OCF_AttractLightning;
static const int OCF_Available;
static const int OCF_Chop;
static const int OCF_Collectible;
static const int OCF_Collection;
static const int OCF_Construct;
static const int OCF_Container;
static const int OCF_CrewMember;
static const int OCF_Entrance;
static const int OCF_Exclusive;
static const int OCF_Fullcon;
static const int OCF_Grab;
static const int OCF_HitSpeed1;
static const int OCF_HitSpeed2;
static const int OCF_HitSpeed3;
static const int OCF_HitSpeed4;
static const int OCF_Inflammable;
static const int OCF_InFree;
static const int OCF_InLiquid;
static const int OCF_InSolid;
static const int OCF_Living;
static const int OCF_NotContained;
static const int OCF_OnFire;
static const int OCF_Rotate;
static const object this;
static const int C4V_Effect;
static const int C4V_Def;
static const int C4V_Function;
static const int C4X_Ver1;
static const int C4X_Ver2;
static const int C4X_Ver3;
static const int FX_OK;
static const int FX_Effect_Deny;
static const int FX_Effect_Annul;
static const int FX_Effect_AnnulDoCalls;
static const int FX_Execute_Kill;
static const int FX_Stop_Deny;
static const int FX_Start_Deny;
static const int FX_Call_Normal;
static const int FX_Call_Temp;
static const int FX_Call_TempAddForRemoval;
static const int FX_Call_RemoveClear;
static const int FX_Call_RemoveDeath;
static const int FX_Call_DmgScript;
static const int FX_Call_DmgBlast;
static const int FX_Call_DmgFire;
static const int FX_Call_Energy;
static const int FX_Call_EngScript;
static const int FX_Call_EngBlast;
static const int FX_Call_EngObjHit;
static const int FX_Call_EngFire;
static const int FX_Call_EngBaseRefresh;
static const int FX_Call_EngAsphyxiation;
static const int FX_Call_EngCorrosion;
static const int FX_Call_EngGetPunched;
static const int FX_Call_DmgChop;
static const int C4M_Vehicle;
static const int C4M_Solid;
static const int C4M_SemiSolid;
static const int C4M_Liquid;
static const int C4M_Background;
static const int SBRD_Caption;
static const int TEAM_Custom;
static const int TEAM_Active;
static const int TEAM_AllowHostilityChange;
static const int TEAM_Dist;
static const int TEAM_AllowTeamSwitch;
static const int TEAM_AutoGenerateTeams;
static const int TEAM_TeamColors;
static const int C4FO_Not;
static const int C4FO_And;
static const int C4FO_Or;
static const int C4FO_Exclude;
static const int C4FO_InRect;
static const int C4FO_AtPoint;
static const int C4FO_AtRect;
static const int C4FO_OnLine;
static const int C4FO_Distance;
static const int C4FO_ID;
static const int C4FO_OCF;
static const int C4FO_Category;
static const int C4FO_Action;
static const int C4FO_ActionTarget;
static const int C4FO_Procedure;
static const int C4FO_Container;
static const int C4FO_AnyContainer;
static const int C4FO_Owner;
static const int C4FO_Controller;
static const int C4FO_Func;
static const int C4FO_InArray;
static const int C4FO_Layer;
static const int MD_DragSource;
static const int MD_DropTarget;
static const int MD_NoClick;
static const int C4SO_Reverse;
static const int C4SO_Multiple;
static const int C4SO_Distance;
static const int C4SO_Random;
static const int C4SO_Speed;
static const int C4SO_Mass;
static const int C4SO_Value;
static const int C4SO_Func;
static const int C4SECT_SaveLandscape;
static const int C4SECT_SaveObjects;
static const int C4SECT_KeepEffects;
static const int TEAMID_New;
static const int MSG_NoLinebreak;
static const int MSG_Bottom;
static const int MSG_Multiple;
static const int MSG_Top;
static const int MSG_Left;
static const int MSG_Right;
static const int MSG_HCenter;
static const int MSG_VCenter;
static const int MSG_DropSpeech;
static const int MSG_WidthRel;
static const int MSG_XRel;
static const int MSG_YRel;
static const int C4PT_User;
static const int C4PT_Script;
static const int CSPF_FixedAttributes;
static const int CSPF_NoScenarioInit;
static const int CSPF_NoEliminationCheck;
static const int CSPF_Invisible;
static const int DMQ_Sky;
static const int DMQ_Sub;
static const int DMQ_Bridge;
static const int PLRZOOM_Direct;
static const int PLRZOOM_NoIncrease;
static const int PLRZOOM_NoDecrease;
static const int PLRZOOM_LimitMin;
static const int PLRZOOM_LimitMax;
static const int PLRZOOM_Set;
static const int C4D_Environment;
static const int C4D_MouseSelect;
static const int C4D_Foreground;
static const int C4D_MouseIgnore;
static const int C4D_IgnoreFoW;
static const int C4D_GrabGet;
static const int C4D_GrabPut;
static const int VIS_All;
static const int VIS_None;
static const int VIS_Owner;
static const int VIS_Allies;
static const int VIS_Enemies;
static const int VIS_Select;
static const int VIS_God;
static const int VIS_LayerToggle;
static const int VIS_OverlayOnly;
static const int C4MN_Style_Normal;
static const int C4MN_Style_Context;
static const int C4MN_Style_Info;
static const int C4MN_Style_Dialog;
static const int C4MN_Style_EqualItemHeight;
static const int C4MN_Extra_None;
static const int C4MN_Extra_Components;
static const int C4MN_Extra_Value;
static const int C4MN_Extra_Info;
static const int C4MN_Add_ImgRank;
static const int C4MN_Add_ImgIndexed;
static const int C4MN_Add_ImgObjRank;
static const int C4MN_Add_ImgObject;
static const int C4MN_Add_ImgTextSpec;
static const int C4MN_Add_ImgColor;
static const int C4MN_Add_PassValue;
static const int C4MN_Add_ForceCount;
static const int C4MN_Add_ForceNoDesc;
static const int C4MN_Add_ImgPropListSpec;
static const int GFXOV_MODE_None;
static const int GFXOV_MODE_Base;
static const int GFXOV_MODE_Action;
static const int GFXOV_MODE_Picture;
static const int GFXOV_MODE_IngamePicture;
static const int GFXOV_MODE_Object;
static const int GFXOV_MODE_ExtraGraphics;
static const int GFXOV_MODE_Rank;
static const int GFXOV_MODE_ObjectPicture;
static const int GFX_Overlay;
static const int GFXOV_Clothing;
static const int GFXOV_Tools;
static const int GFXOV_ProcessTarget;
static const int GFXOV_Misc;
static const int GFXOV_UI;
static const int GFX_BLIT_Additive;
static const int GFX_BLIT_Mod2;
static const int GFX_BLIT_ClrSfc_OwnClr;
static const int GFX_BLIT_ClrSfc_Mod2;
static const int GFX_BLIT_Wireframe;
static const int GFX_BLIT_Custom;
static const int GFX_BLIT_Parent;
static const int CNAT_None;
static const int CNAT_Left;
static const int CNAT_Right;
static const int CNAT_Top;
static const int CNAT_Bottom;
static const int CNAT_Center;
static const int CNAT_MultiAttach;
static const int CNAT_NoCollision;
static const int VTX_X;
static const int VTX_Y;
static const int VTX_CNAT;
static const int VTX_Friction;
static const int VTX_SetPermanent;
static const int VTX_SetPermanentUpd;
static const int C4OS_DELETED;
static const int C4OS_NORMAL;
static const int C4OS_INACTIVE;
static const int C4CMD_Base;
static const int C4CMD_SilentBase;
static const int C4CMD_Sub;
static const int C4CMD_SilentSub;
static const int C4CMD_MoveTo_NoPosAdjust;
static const int C4CMD_MoveTo_PushTarget;
static const int C4CMD_Enter_PushTarget;
static const int C4AVP_Const;
static const int C4AVP_X;
static const int C4AVP_Y;
static const int C4AVP_R;
static const int C4AVP_AbsX;
static const int C4AVP_AbsY;
static const int C4AVP_XDir;
static const int C4AVP_YDir;
static const int C4AVP_RDir;
static const int C4AVP_CosR;
static const int C4AVP_SinR;
static const int C4AVP_CosV;
static const int C4AVP_SinV;
static const int C4AVP_Action;
static const int C4AVP_Linear;
static const int C4AVP_Dist;
static const int C4AVP_AbsRDir;
static const int ANIM_Loop;
static const int ANIM_Hold;
static const int ANIM_Remove;
static const int AM_None;
static const int AM_DrawBefore;
static const any nil;

global func any _inherited();
global func int Abs(int value);
global func bool ActIdle();
global func bool AddCommand(string command, object target, int x, int y, object target2, int delay, any data, int retries, int base_mode);
global func proplist AddEffect(string name, object target, int priority, int timer, object command_target, any command_target_id, any var1, any var2, any var3, any var4);
global func int AddMenuItem(string caption, string command, id symbol, int count, any parameter, string info_caption, int extra, any xpar1, any xpar2);
global func int AddMsgBoardCmd(string command, string script);
global func int AddVertex(int x, int y);
global func int Angle(int x1, int y1, int x2, int y2, int precision);
global func bool AppendCommand(string command, object target, any x, any y, object target2, int delay, any data, int retries, int base_mode);
global func int ArcCos(int value, int radius);
global func int ArcSin(int value, int radius);
global func int AttachMesh(any mesh, string parent_bone, string child_bone, array transformation, int flags);
global func int BoundBy(int value, int lower_bound, int upper_bound);
global func bool Bubble(int x, int y);
global func id C4Id(string id_string);
global func any Call(function|string function);
global func bool CanConcatPictureWith(object other);
global func bool CastParticles(string name, int amount, int level, int x, int y, int a0, int a1, int b0, int b1, object obj);
global func bool ChangeDef(id new_def);
global func bool CheckConstructionSite(id object_id, int xoffset, int yoffset);
global func int CheckEffect(string name, object target, int priority, int timer, any var1, any var2, any var3, any var4);
global func bool CheckVisibility(int player);
global func int ClearMenuItems();
global func bool ClearParticles(string name, object obj);
global func bool CloseMenu();
global func bool Collect(object item);
global func bool ComponentAll(id components);
global func object ComposeContents(id object_id);
global func any Construction(object creator);
global func object Contained();
global func object Contents(int index);
global func int ContentsCount(id object_id);
global func int Cos(int angle, int radius, int precision);
global func array CreateArray(int length);
global func object CreateConstruction(id object_id, int xoffset, int yoffset, int owner, int completion, bool adjust_terrain, bool check_site);
global func object CreateContents(id id, int count);
global func bool CreateMenu(id symbol, object command_object, int extra, string caption, int extra_data, int style, bool permanent, id menu_id);
global func object CreateObject(id id, int xoffset, int yoffset, int owner);
global func object CreateObjectAbove(id id, int xoffset, int yoffset, int owner);
global func bool CreateParticle(string name, int|array x, int|array y, int|array speedX, int|array speedY, int|array lifetime, proplist properties, int amount);
global func array PV_Linear(any start_value, any end_value);
global func array PV_Random(any start_value, any end_value, any reroll_interval);
global func array PV_Direction(any factor);
global func array PV_Step(any step, any start_value, any delay);
global func array PV_KeyFrames(any smoothing, any position1, any value1, any position2, any value2);
global func array PV_Speed(any factor, any start_value);
global func array PV_Wind(int strength);
global func array PV_Gravity(int val);
global func array PC_Die();
global func array PC_Bounce(int bounciness);
global func array PC_Stop();
global func bool CreateParticleAtBone(string szName, string szBoneName, array pos, array dir, int a, int b, object target, bool behind_target);
global func bool CreateScriptPlayer(string name, int color, int team, int flags, id extra_data);
global func bool CustomMessage(string message, object obj, int plr, int offset_x, int offset_y, int color, id deco, any portrait, int flags);
global func any DeathAnnounce();
global func any Definition(proplist def);
global func bool DetachMesh(int attach_number);
global func int DigFree(int x, int y, int radius, bool no_dig2objects);
global func int DigFreeRect(int x, int y, int width, int height, bool no_dig2objects);
global func int Distance(int x1, int y1, int x2, int y2);
global func bool DoBreath(int change);
global func any DoCon(int change);
global func any DoCrewExp(int change);
global func any DoDamage(int change, int damage_type, int caused_by);
global func any DoEnergy(int change, bool exact, int damage_type, int caused_by);
global func bool DoHomebaseMaterial(int player, id definition, int change);
global func bool DoHomebaseProduction(int player, id type, int change);
global func bool DoPlayerScore(int player, int change);

global func bool DoScoreboardShow(int change, int for_player);
global func bool DrawDefMap(int x, int y, int width, int height, string map_name);
global func bool DrawMap(int x, int y, int width, int height, string map);
global func bool DrawMaterialQuad(string szMaterialTexture, int x1, int y1, int x2, int y2, int x3, int y3, int x4, int y4, bool sub);
global func object EditCursor();
global func any EffectCall(object target, proplist effect, string command);
global func bool EliminatePlayer(int player);
global func bool Enter(object target);
global func any eval(string script);
global func bool Exit(int x, int y, int r, int xdir, int ydir, int rdir);
global func int ExtractMaterialAmount(int x, int y, int material_index, int amount);
global func bool FatalError(string message);
global func array FindConstructionSite(id definition, int x, int y);
global func object FindContents(id type);
global func object FindObject(array criteria);
global func array FindObjects(array criteria);
global func object FindOtherContents(id type);
global func bool FinishCommand(bool success, int command_num);
global func any Fling(int xdir, int ydir, int precision, bool add_speed);

global func string Format(string text);
global func int FrameCounter();
global func any FreeRect(int x, int y, int width, int height, int density);
global func bool GainMissionAccess(string password);
global func any GameCallEx(string function);
global func bool GameOver();
global func bool GBackLiquid(int x, int y);
global func bool GBackSemiSolid(int x, int y);
global func bool GBackSky(int x, int y);
global func bool GBackSolid(int x, int y);
global func string GetAction();
global func object GetActionTarget(int index);
global func int GetActTime();
global func bool GetAlive();
global func int GetAnimationLength(string animation);
global func string GetAnimationName(int animation_number);
global func int GetAnimationPosition(int animation_number);
global func int GetAnimationWeight(int animation_number);
global func int GetBreath();
global func int GetCategory();
global func int GetChar(string text, int index);
global func int GetClimate();
global func int GetClrModulation(int overlay_id);
global func int GetColor();
global func int GetComDir();
global func any GetCommand(int element, int command_num);
global func int|id GetComponent(id component, int index, object obj, id definition);
global func int GetCon();
global func int GetContact(int index, int dwCNAT);
global func int GetController();
global func bool SetController(int controller);
global func object GetCrew(int player, int index);
global func int GetCrewCount(int player);
global func bool GetCrewEnabled();
global func any GetCrewExtraData(string data_name);
global func object GetCursor(int player);
global func int GetDamage();
global func int GetDefBottom();
global func any GetDefCoreVal(string entry, string section, int entry_number);
global func id GetDefinition(int index);
global func int GetDir();
global func any GetEffect(string name, object target, int index, int max_priority);
global func int GetEffectCount(string mask, object target, int max_priority);
global func int GetEnergy();
global func bool GetEntrance();
global func int GetGravity();
global func object GetHiRank(int player);
global func int GetHomebaseMaterial(int player, id id, int index, int category);
global func int GetHomebaseProduction(int player, id id, int index, int category);
global func id GetID();
global func int GetIndexOf(array array2search, any needle);
global func int GetKiller();
global func int GetLength(string|array text);
global func int GetMass();
global func int GetMaterial(int x, int y);
global func int GetMaterialCount(int material_index);
global func any GetMaterialVal(string entry, string section, int material, int entry_number);
global func any GetMenu();
global func any GetMenuSelection();
global func string GetMeshMaterial(int submesh);
global func bool GetMissionAccess(string mission_access);
global func string GetName();
global func string GetNeededMatStr();
global func int GetObjectBlitMode(int overlay_id);
global func any GetObjectInfoCoreVal(string entry, string section, int entry_number);
global func any GetObjectVal(string entry, string section, int entry_number);
global func int GetOCF();
global func int GetOwner();
global func int GetPathLength(int startx, int starty, int endx, int endy);
global func int GetPhase();
global func int GetPlayerByIndex(int index, int player_type);
global func string GetPlayerControlAssignment(int player, int control, bool human_readable, bool short_name);
global func int GetPlayerCount(int player_type);
global func int GetStartupPlayerCount();
global func int GetPlayerID(int player);
global func any GetPlayerInfoCoreVal(string entry, string section, int player, int entry_number);
global func string GetPlayerName(int player);
global func int GetPlayerScore(int player);
global func int GetPlayerScoreGain(int player);
global func int GetPlayerTeam(int player);

global func int GetPlayerType(int player);
global func any GetPlayerVal(string entry, string section, int player, int entry_number);
global func int GetPlrClonkSkin(int player);
global func int GetPlrColor(int player);
global func any GetPlrExtraData(int player, string data_name);
global func int GetPlrKnowledge(int player, id type, int index, int category);
global func object GetPlrView(int player);

global func int GetPlrViewMode(int player);
global func string GetProcedure();
global func array[string] GetProperties(proplist object);
global func any GetProperty(string key, proplist object);
global func int GetR();
global func int GetRank();
global func int GetRDir(int precision);

global func int GetRootAnimation(int slot);
global func any GetScenarioVal(string entry, string section, int entry_number);
global func int GetSeason();
global func int GetSkyAdjust(bool back_color);
global func int GetTeamByIndex(int index);
global func int GetTeamColor(int team);
global func int GetTeamCount();
global func string GetTeamName(int team);
global func int GetTemperature();
global func int GetTime();
global func int GetType(any value);
global func int GetUnusedOverlayID(int base_index);
global func int GetValue(object base, int for_player);
global func int GetVertex(int index, int data);
global func int GetVertexNum();
global func int GetWealth(int owner);
global func int GetWind(int x, int y, bool global);
global func int GetX();
global func int GetXDir(int precision);
global func int GetY();
global func int GetYDir(int precision);
global func bool GrabContents(object obj);
global func bool GrabObjectInfo(object from);
global func bool Hostile(int player1, int player2, bool check_one_way);
global func any inherited();
global func bool InLiquid();
global func bool InsertMaterial(int material_index, int x, int y, int xdir, int ydir, proplist out_insertpos);
global func bool CanInsertMaterial(int mat, int x, int y, proplist insert_position);
global func bool Inside(int value, int lower_bound, int upper_bound);
global func bool IsNetwork();
global func bool Jump();
global func bool Kill(object obj, bool forced);
global func int LandscapeHeight();
global func int LandscapeWidth();
global func bool LaunchEarthquake(int x, int y);
global func bool LaunchLightning(int x, int y, int xspeed, int xrange, int yspeed, int yrange, bool do_gamma);
global func bool LaunchVolcano(int x, int y, int strength, string material_name);
global func bool Log(string message, ...);
global func bool MakeCrewMember(int player);
global func int Material(string material_name);
global func string MaterialName(int material_index);
global func int Max(int value1, int value2);
global func bool Message(string message, ...);
global func int Min(int value1, int value2);
global func int Music(string song_name, bool loop);
global func int MusicLevel(int level);
global func object Object(int object_number);
global func int ObjectCount(array criteria);
global func int ObjectDistance(object obj2, object obj);
global func int ObjectNumber();
global func any Par(int index);
global func bool PathFree(int x1, int y1, int x2, int y2);
global func object PlaceAnimal(id animal_id);
global func object PlaceVegetation(id id, int x, int y, int width, int height, int growth);
global func int PlayAnimation(string animation, int slot, array position, array weight, int sibling);
global func bool PlayerMessage(int player, string message, ...);
global func bool Punch(object obj, int strength);
global func bool PushParticles(string name, int xacc, int yacc);
global func int Random(int max);
global func bool ReloadDef(id definition);
global func bool ReloadParticle(string particle);
global func bool RemoveEffect(string name, object target, proplist effect, bool no_calls);
global func any RemoveObject(bool eject_contents);
global func int RemoveVertex(int index);
global func bool ResetGamma(int ramp_index);
global func bool ResetPhysical(string physical);
global func int ScoreboardCol(id definition);
global func object ScrollContents();
global func bool SelectMenuItem(int number);
global func bool SetAction(string action, object target1, object target2, bool force);
global func bool SetActionData(any data);
global func any SetActionTargets(object target1, object target2);
global func int SetAlive(bool alive);
global func bool SetAnimationPosition(int animation_number, array position);
global func bool SetAnimationWeight(int animation_number, array weight);
global func bool SetAttachBones(int attach_number, string parent_bone, string child_bone);
global func int TransformBone(string bone_name, array transformation, int slot, array weightProvider, int sibling, int attach_number);
global func bool SetAttachTransform(int attach_number, array transformation);
global func bool SetBridgeActionData(int bridge_length, bool move_clonk, bool build_wall, int bridge_material);
global func any SetCategory(int category);
global func any SetClimate(int temperature);
global func bool SetClrModulation(int color, int overlay_id);
global func any SetColor(int color);
global func int SetComDir(int com_dir);
global func bool SetCommand(string command, object target, int x, int y, object target2, any data, int retries);
global func bool SetComponent(id component, int count);
global func any SetCrewEnabled(bool enabled);
global func any SetCrewExtraData(string data_name, any data);

global func bool SetCrewStatus(int player, bool into_crew);
global func bool SetCursor(int player, object obj, bool no_select_arrow);
global func int SetDir(int dir);
global func any SetEntrance(bool status);
global func int SetFilmView(int for_player);
global func any SetFoW(bool enabled, int player);
global func bool SetGameSpeed(int game_speed);
global func bool SetGamma(int color1, int color2, int color3, int ramp_index);
global func bool SetGraphics(string gfx_name, id source_definition, int overlay, int overlay_mode, string action, int dwBlitMode, object overlay_object);
global func any SetGravity(int gravity);
global func bool SetHostility(int player1, int player2, bool hostile, bool silent, bool no_calls);
global func bool SetKiller(int new_killer);
global func int SetLength(array resize, int size);
global func any SetMass(int mass);
global func bool SetMatAdjust(int colorMod);
global func bool SetMaxPlayer(int max);
global func bool SetMenuSize(int coloumns, int rows);
global func bool SetMeshMaterial(string material, int submesh);
global func bool SetName(string name, bool set_permanent, bool make_valid_if_exists);
global func bool SetObjDrawTransform(int width, int xskew, int xadjust, int yskew, int height, int yadjust, int overlay_id);
global func int SetObjectBlitMode(int dwNewBlitMod, int overlay_id);
global func bool SetOwner(int new_owner);
global func bool SetPhase(int phase);
global func bool SetPhysical(string physical, int value, int mode);
global func any SetPicture(int x, int y, int width, int height);
global func int SetPlayerTeam(int player, int new_team, bool no_calls);
global func bool SetPlayerViewLock(int player, bool locked);
global func bool SetPlayerZoomByViewRange(int player, int range_x, int range_y, int flags);
global func int SetPlayList(string playlist);
global func any SetPlrExtraData(int player, string data_name, any data);
global func int SetPlrKnowledge(int player, id definition, bool remove);
global func int SetPlrMagic(int player, id id, bool remove);
global func bool SetPlrView(int player, object obj);
global func any SetPlrViewRange(int range);
global func any SetPosition(int x, int y, bool check_bounds);
global func bool SetProperty(string key, any value, proplist obj);
global func bool SetR(int angle);
global func bool SetRDir(int rdir, int precision);

global func bool SetScoreboardData(int row_id, int coloumn_id, string text, int data);
global func any SetSeason(int season);
global func any SetShape(int x, int y, int width, int height);
global func bool SetSkyAdjust(int colorMod, int backgroundColor);
global func bool SetSkyParallax(int mode, int xpar, int ypar, int xdir, int ydir, int x, int y);
global func any SetSolidMask(int x, int y, int width, int height, int target_x, int target_y);
global func any SetTemperature(int temperature);
global func bool SetTransferZone(int x, int y, int width, int height);
global func int SetVertex(int index, int select, int value, int set_custom_permanent);
global func bool SetViewOffset(int player, int x, int x);
global func bool SetWealth(int player, int value);
global func any SetWind(int strength);
global func bool SetXDir(int xdir, int precision);
global func bool SetYDir(int ydir, int precision);
global func any ShakeFree(int x, int y, int radius);
global func any ShakeObjects(int x, int y, int radius);
global func bool ShowInfo();
global func array SimFlight(int x, int y, int xdir, int ydir, int min_density, int max_density, int iterations, int precision);
global func int Sin(int angle, int radius, int precision);
global func bool SortArray(array array2sort, bool descending);
global func bool SortArrayByArrayElement(array array2sort, int element_index, bool descending);
global func bool SortArrayByProperty(array array2sort, string property_name, bool descending);
global func bool SortScoreboard(int coloumn_id, bool reverse);
global func bool Sound(string name, bool global, int volume, int player, int loop_count, bool multiple, int customFallOffDistance);
global func bool SoundAt(string sound, int iX, int iY, int iLevel, int atPlayer, int customFalloffDistance, int pitch);

static const int C4SMT_None;
static const int C4SMT_Reverb;
static const int C4SMT_Echo;
static const int C4SMT_Equalizer;

global func bool ChangeSoundModifier(proplist modifier_props, bool release);

global func int Sqrt(int value);
global func bool StartScriptProfiler(id definition_script);
global func bool StopAnimation(int animation_number);
global func bool StopScriptProfiler();
global func bool Stuck();
global func string Translate(string text);
global func string WildcardMatch(string text, string wildcard);
global func any CreatePropList(any prototype);
global func any ResetProperty(any key, any obj);
global func any DebugLog(any pars, ...);
global func any AsyncRandom(int range);
global func any LocateFunc(any funcname, any p);
global func any ModulateColor(int clr1, int clr2);
global func any StartCallTrace();
global func any GetConstantNameByValue(int value, any name_prefix, int idx);
global func any IncinerateLandscape(int x, int y);
global func any GetPlayerColor(int player);
global func any GetTexture(int x, int y);
global func any GetAverageTextureColor(string texture);
global func any BlastFree(int x, int y, int level, int causedBy);
global func any AddMessage(any pars, ...);
global func any ResetCursorView(int plr);
global func any SurrenderPlayer(int plr);
global func any SetLeaguePerformance(int score);
global func any GetViewCursor(int plr);
global func any SetViewCursor(int plr, any obj);
global func any ClearFreeRect(int x, int y, int wdt, int hgt);
global func any PathFree2(any x1, any y1, any x2, any y2);
global func any GetLeague(int idx);
global func any TestMessageBoard(int forPlr, bool testIfInUse);
global func any CallMessageBoard(any obj, bool upperCase, any szQueryString, int forPlr);
global func any AbortMessageBoard(any obj, int forPlr);
global func any OnMessageBoardAnswer(any obj, int forPlr, any szAnswerString);
global func any GetMatAdjust();
global func any DrawMatChunks(int tx, int ty, int twdt, int thgt, int icntx, int icnty, any strMaterial, any strTexture, bool bIFT);
global func any CastAParticles(any szName, int amount, int level, int x, int y, int a0, int a1, int b0, int b1, any obj, bool back);
global func any CastBackParticles(any szName, int amount, int level, int x, int y, int a0, int a1, int b0, int b1, any obj);
global func any SetTextureIndex(any psMatTex, int newIndex, bool insert);
global func any RemoveUnusedTexMapEntries();
global func any LoadScenarioSection(any pstrSection, int dwFlags);
global func any SetPreSend(int toVal, any newName);
global func any GetTeamConfig(int configValue);
global func any InitScenarioPlayer(int player, int team);
global func any GetScoreboardString(int rowID, int colID);
global func any GetScoreboardData(int rowID, int colID);
global func any AddEvaluationData(any text, int player);
global func any HideSettlementScoreInEvaluation(bool hide);
global func any ActivateGameGoalMenu(int player);
global func any PauseGame(bool toggle);
global func any SetNextMission(any szNextMission, any szNextMissionText, any szNextMissionDesc);
global func any GetPlayerControlState(int plr, int control);
global func any SetPlayerControlEnabled(int plr, int ctrl, bool is_enabled);
global func any GetPlayerControlEnabled(int plr, int ctrl);
global func any ExecuteCommand();
global func any SetMenuDecoration(any newDeco);
global func any SetMenuTextProgress(int newProgress);
global func any GetObjectLayer();
global func any SetObjectLayer(any newLayer);
global func any SetObjDrawTransform2(int a, int b, int c, int d, int e, int f, int g, int h, int i, int overlayID);
global func any SetObjectStatus(int newStatus, bool clearPointers);
global func any GetObjectStatus();
global func any AdjustWalkRotation(int rangeX, int rangeY, int speed);
global func any DoNoCollectDelay(int change);
global func any this(); 

static const proplist MapLayer;
static const proplist Map;
static const int MAPALGO_Layer;
static const int MAPALGO_RndChecker;
static const int MAPALGO_And;
static const int MAPALGO_Or;
static const int MAPALGO_Xor;
static const int MAPALGO_Not;
static const int MAPALGO_Scale;
static const int MAPALGO_Offset;
static const int MAPALGO_Rect;
static const int MAPALGO_Ellipsis;
static const int MAPALGO_Polygon;
static const int MAPALGO_Turbulence;
static const int MAPALGO_Border;
static const int MAPALGO_Lines;
static const int MAPALGO_Rotate;

static const int GUI_SetTag;
static const int GUI_Call;
static const int GUI_GridLayout;
static const int GUI_VerticalLayout;
static const int GUI_TextVCenter;
static const int GUI_TextHCenter;
static const int GUI_TextRight;
static const int GUI_TextBottom;
static const int GUI_TextTop;
static const int GUI_TextLeft;
static const int GUI_FitChildren;
static const int GUI_Multiple;
static const int GUI_IgnoreMouse;
static const int GUI_NoCrop;

global func int CustomGuiOpen(proplist menu);
global func bool CustomGuiSetTag(string tag, int menuID, int childID, object target);
global func bool CustomGuiClose(int menuID, int childID, object target);
global func bool CustomGuiUpdate(proplist update, int menuID, int childID, object target);

global func bool Draw(string mattex, proplist mask_algo, array rect);
global func bool Blit(proplist mask_algo, array rect);
global func proplist CreateLayer(string mattex_fill, int width, int height);
global func proplist Duplicate(any mask_spec, array rect);
global func int GetPixel(int x, int y);
global func bool SetPixel(int x, int y, any to_value);
global func int GetPixelCount(any mask_spec, array rect);
global func bool Resize(int new_wdt, int new_hgt);
global func bool FindPosition(proplist out_pos, any mask_spec);
global func array CreateMatTexMask(any mask_spec);

global func bool FileWrite(int handle, string data);

static const object Global;

static const int ATTACH_Front;
static const int ATTACH_Back;
static const int ATTACH_MoveRelative;

global func bool SetLeagueProgressData(string newData, int player);
global func string GetLeagueProgressData(int player);

global func array PV_Sin(int|array value, int|array amplitude, int|array offset);

global func array Trans_Identity();
global func array Trans_Translate(int dx, int dy, int dz);
global func array Trans_Scale(int sx, int sy, int sz);
global func array Trans_Rotate(int angle, int rx, int ry, int rz);
global func array Trans_Mul(array lhs, array rhs);

global func bool GainScenarioAchievement(string achievement_name, int avalue, int player, string for_scenario);

global func int GetPXSCount();

global func void SetLightRange(int range, int fadeout_range);
global func void SetLightColor(object obj, int value);

global func void SetAmbientBrightness(int brightness);
global func int GetAmbientBrightness();