static const int C4D_All;
static const int C4D_Background;
static const int C4D_Goal;
static const int C4D_Knowledge;
static const int C4D_Living;
static const int C4D_Object;
static const int C4D_Parallax;
static const int C4D_Rule;
static const int C4D_StaticBack;
static const int C4D_Structure;
static const int C4D_Vehicle;
static const int C4D_SelectMaterial;
static const int C4D_SelectHomebase;
static const int C4D_SelectKnowledge;
static const int C4D_SelectBuilding;
static const int C4D_SelectInEarth;
static const int C4D_SelectVehicle;
static const int C4D_SelectAnimal;
static const int C4D_Environment;
static const int C4D_Magic;
static const int C4D_MouseSelect;
static const int C4D_Foreground;
static const int C4D_MouseIgnore;
static const int C4D_IgnoreFoW;
static const int C4D_GrabGet;
static const int C4D_GrabPut;
static const int C4D_LinePower;
static const int C4D_LineSource;
static const int C4D_LineDrain;
static const int C4D_LineLightning;
static const int C4D_LineVolcano;
static const int C4D_LineRope;
static const int C4D_LineColored;
static const int C4D_LineVertex;
static const int C4D_PowerInput;
static const int C4D_PowerOutput;
static const int C4D_LiquidInput;
static const int C4D_LiquidOutput;
static const int C4D_PowerGenerator;
static const int C4D_PowerConsumer;
static const int C4D_LiquidPump;
static const int C4D_EnergyHolder;

static const int C4V_Any;
static const int C4V_Array;
static const int C4V_Bool;
static const int C4V_C4ID;
static const int C4V_C4Object;
static const int C4V_Int;
static const int C4V_String;
static const int C4V_PropList;

static const int COMD_Down;
static const int COMD_DownLeft;
static const int COMD_DownRight;
static const int COMD_Left;
static const int COMD_None;
static const int COMD_Right;
static const int COMD_Stop;
static const int COMD_Up;
static const int COMD_UpLeft;
static const int COMD_UpRight;

static const int MD_NoClick;
static const int MD_DropTarget;
static const int MD_DragSource;

static const int DIR_Left;
static const int DIR_Right;

static const int NO_OWNER;

static const int OCF_Alive;
static const int OCF_AttractLightning;
static const int OCF_Available;
static const int OCF_Chop;
static const int OCF_Collectible;
static const int OCF_Collection;
static const int OCF_Construct;
static const int OCF_Container;
static const int OCF_CrewMember;
static const int OCF_Edible;
static const int OCF_Entrance;
static const int OCF_Exclusive;
static const int OCF_FightReady;
static const int OCF_Fullcon;
static const int OCF_Grab;
static const int OCF_HitSpeed1;
static const int OCF_HitSpeed2;
static const int OCF_HitSpeed3;
static const int OCF_HitSpeed4;
static const int OCF_Inflammable;
static const int OCF_InFree;
static const int OCF_InLiquid;
static const int OCF_InSolid;
static const int OCF_LineConstruct;
static const int OCF_Living;
static const int OCF_NotContained;
static const int OCF_OnFire;
static const int OCF_PowerConsumer;
static const int OCF_PowerSupply;
static const int OCF_Prey;
static const int OCF_Rotate;

static const int VIS_All;
static const int VIS_Allies;
static const int VIS_Enemies;
static const int VIS_God;
static const int VIS_Local;
static const int VIS_None;
static const int VIS_Owner;

static const int CON_CursorLeft;
static const int CON_CursorToggle;
static const int CON_CursorRight;
static const int CON_Throw;
static const int CON_Up;
static const int CON_Dig;
static const int CON_Left;
static const int CON_Down;
static const int CON_Right;
static const int CON_Menu;
static const int CON_Special;
static const int CON_Special2;

static const int VIS_Select;
static const int VIS_LayerToggle;
static const int VIS_OverlayOnly;

static const int C4X_Ver1;
static const int C4X_Ver2;
static const int C4X_Ver3;
static const int C4X_Ver4;
static const int C4X_VerBuild;

static const int SkyPar_Keep;

static const int C4MN_Style_Normal;
static const int C4MN_Style_Context;
static const int C4MN_Style_Info;
static const int C4MN_Style_Dialog;
static const int C4MN_Style_EqualItemHeight;
static const int C4MN_Extra_None;
static const int C4MN_Extra_Components;
static const int C4MN_Extra_Value;
static const int C4MN_Extra_MagicValue;
static const int C4MN_Extra_Info;
static const int C4MN_Extra_ComponentsMagic;
static const int C4MN_Extra_LiveMagicValue;
static const int C4MN_Extra_ComponentsLiveMagic;
static const int C4MN_Add_ImgRank;
static const int C4MN_Add_ImgIndexed;
static const int C4MN_Add_ImgObjRank;
static const int C4MN_Add_ImgObject;
static const int C4MN_Add_ImgTextSpec;
static const int C4MN_Add_ImgColor;
static const int C4MN_Add_PassValue;
static const int C4MN_Add_ForceCount;
static const int C4MN_Add_ForceNoDesc;

static const int FX_OK;
static const int FX_Effect_Deny;
static const int FX_Effect_Annul;
static const int FX_Effect_AnnulDoCalls;
static const int FX_Execute_Kill;
static const int FX_Stop_Deny;
static const int FX_Start_Deny;
static const int FX_Call_Normal;
static const int FX_Call_Temp;
static const int FX_Call_TempAddForRemoval;
static const int FX_Call_RemoveClear;
static const int FX_Call_RemoveDeath;
static const int FX_Call_DmgScript;
static const int FX_Call_DmgBlast;
static const int FX_Call_DmgFire;
static const int FX_Call_DmgChop;
static const int FX_Call_Energy;
static const int FX_Call_EngScript;
static const int FX_Call_EngBlast;
static const int FX_Call_EngObjHit;
static const int FX_Call_EngFire;
static const int FX_Call_EngBaseRefresh;
static const int FX_Call_EngAsphyxiation;
static const int FX_Call_EngCorrosion;
static const int FX_Call_EngStruct;
static const int FX_Call_EngGetPunched;

static const int GFXOV_MODE_None;
static const int GFXOV_MODE_Base;
static const int GFXOV_MODE_Action;
static const int GFXOV_MODE_Picture;
static const int GFXOV_MODE_IngamePicture;
static const int GFXOV_MODE_Object;
static const int GFXOV_MODE_ExtraGraphics;
static const int GFXOV_Clothing;
static const int GFXOV_Tools;
static const int GFXOV_ProcessTarget;
static const int GFXOV_Misc;
static const int GFXOV_UI;
static const int GFXOV_MODE_Rank;
static const int GFXOV_MODE_ObjectPicture;

static const int GFX_Overlay;
static const int GFX_BLIT_Additive;
static const int GFX_BLIT_Mod2;
static const int GFX_BLIT_ClrSfc_OwnClr;
static const int GFX_BLIT_ClrSfc_Mod2;
static const int GFX_BLIT_Custom;
static const int GFX_BLIT_Parent;

static const int CNAT_None;
static const int CNAT_Left;
static const int CNAT_Right;
static const int CNAT_Top;
static const int CNAT_Bottom;
static const int CNAT_Center;
static const int CNAT_MultiAttach;
static const int CNAT_NoCollision;

static const int VTX_X;
static const int VTX_Y;
static const int VTX_CNAT;
static const int VTX_Friction;
static const int VTX_SetPermanent;
static const int VTX_SetPermanentUpd;

static const int C4M_Vehicle;
static const int C4M_Solid;
static const int C4M_SemiSolid;
static const int C4M_Liquid;
static const int C4M_Background;

static const int SBRD_Caption;

static const int TEAM_Custom;
static const int TEAM_Active;
static const int TEAM_AllowHostilityChange;
static const int TEAM_Dist;
static const int TEAM_AllowTeamSwitch;
static const int TEAM_AutoGenerateTeams;
static const int TEAM_TeamColors;

static const int C4OS_DELETED;
static const int C4OS_NORMAL;
static const int C4OS_INACTIVE;

static const int C4MSGCMDR_Escaped;
static const int C4MSGCMDR_Plain;
static const int C4MSGCMDR_Identifier;

static const int C4FO_Not;
static const int C4FO_And;
static const int C4FO_Or;
static const int C4FO_Exclude;
static const int C4FO_InRect;
static const int C4FO_AtPoint;
static const int C4FO_AtRect;
static const int C4FO_OnLine;
static const int C4FO_Distance;
static const int C4FO_ID;
static const int C4FO_OCF;
static const int C4FO_Category;
static const int C4FO_Action;
static const int C4FO_ActionTarget;
static const int C4FO_Container;
static const int C4FO_AnyContainer;
static const int C4FO_Owner;
static const int C4FO_Controller;
static const int C4FO_Func;
static const int C4FO_Layer;
static const int C4FO_Procedure;

static const int C4SO_Reverse;
static const int C4SO_Multiple;
static const int C4SO_Distance;
static const int C4SO_Random;
static const int C4SO_Speed;
static const int C4SO_Mass;
static const int C4SO_Value;
static const int C4SO_Func;

static const int PHYS_Current;
static const int PHYS_Permanent;
static const int PHYS_Temporary;
static const int PHYS_StackTemporary;

static const int C4CMD_Base;
static const int C4CMD_SilentBase;
static const int C4CMD_Sub;
static const int C4CMD_SilentSub;
static const int C4CMD_MoveTo_NoPosAdjust;
static const int C4CMD_MoveTo_PushTarget;
static const int C4CMD_Enter_PushTarget;

static const int C4SECT_SaveLandscape;
static const int C4SECT_SaveObjects;
static const int C4SECT_KeepEffects;

static const int TEAMID_New;

static const int MSG_NoLinebreak;
static const int MSG_Bottom;
static const int MSG_Multiple;
static const int MSG_Top;
static const int MSG_Left;
static const int MSG_Right;
static const int MSG_HCenter;
static const int MSG_VCenter;
static const int MSG_DropSpeech;
static const int MSG_WidthRel;
static const int MSG_XRel;
static const int MSG_YRel;

static const int C4PT_User;
static const int C4PT_Script;

static const int CSPF_FixedAttributes;
static const int CSPF_NoScenarioInit;
static const int CSPF_NoEliminationCheck;
static const int CSPF_Invisible;

static const any nil;

static const int ANIM_Hold;
static const int ANIM_Loop;
static const int ANIM_Remove;

static const int C4AVP_Const;
static const int C4AVP_Linear;
static const int C4AVP_X;
static const int C4AVP_Y;
static const int C4AVP_AbsX;
static const int C4AVP_AbsY;
static const int C4AVP_XDir;
static const int C4AVP_YDir;
static const int C4AVP_RDir;
static const int C4AVP_CosR;
static const int C4AVP_SinR;
static const int C4AVP_CosV;
static const int C4AVP_SinV;
static const int C4AVP_Action;

static const int DMQ_Sky;
static const int DMQ_Sub;
static const int DMQ_Bridge;

static const int PLRZOOM_Direct;
static const int PLRZOOM_NoIncrease;
static const int PLRZOOM_NoDecrease;
static const int PLRZOOM_LimitMin;
static const int PLRZOOM_LimitMax;

static const int AM_None;
static const int AM_DrawBefore;

global func int AttachMesh(mesh, string szParentBone, string szChildBone, array Transformation, int Flags);
global func int GetAnimationLength(string animation);
global func string GetAnimationName(int animation_number);
global func int PlayAnimation(string szAnimation, int iSlot, array PositionProvider, array WeightProvider, int iSibling, int iAttachNumber);
global func int GetAnimationPosition(int iAnimationNumber, int iAttachNumber);
global func int GetAnimationWeight(int iAnimationNumber, int iAttachNumber);
global func int GetPlayerControlState(int player, int iControl);
global func int GetRootAnimation(int iSlot, int iAttachNumber);
global func bool SetAnimationPosition(int iAnimationNumber, array PositionProvider, int iAttachNumber);
global func bool SetAnimationWeight(int iAnimationNumber, array WeightProvider, int iAttachNumber);
global func bool SetPlayerControlEnabled(int player, int ctrl, bool is_enabled);
global func bool StopAnimation(int iAnimationNumber, int iAttachNumber);
global func bool DetachMesh(int iAttachNumber);
global func bool SetMeshMaterial(string material, int sub_mesh);

global func ResetCursorView(int plr);
global func string Translate(string text);

global func int Abs(int iValue);
global func int AbsX(int x);
global func int AbsY(int y);
global func bool ActIdle();
global func bool Activate(object obj);
global func bool AddCommand(string szCommand, object pTarget, x, y, pTarget2, int iInterval, Data, int iRetries, int iBaseMode);
global func proplist AddEffect(string szEffectName, object pTarget, int iPrio, int iTimerIntervall, object pCmdTarget, idCmdTarget, var1, var2, var3, var4);
global func int AddMenuItem(string szCaption, string szCommand, id idItem, int iCount, iParameter, string szInfoCaption, int iExtra, XPar1, XPar2);
global func int AddMsgBoardCmd(string strCommand, string strScript, int restriction);
global func int AddVertex(int x, int y);
global func int Angle(int x1, int y1, int x2, int y2, int iPrec);
global func int AnyContainer();
global func bool AppendCommand(string szCommand, object pTarget, x, y, pTarget2, int iInterval, Data, int iRetries, int iBaseMode);
global func int ArcCos(int iVal, int iRadius);
global func int ArcSin(int iVal, int iRadius);
global func int BlastObjects(int x, int y, int iLevel, object pContainer, int iCausedBy);
global func int BoundBy(int iVal, int iRange1, int iRange2);
global func bool Bubble(int x, int y);
global func object Buy(id idBuyObj, int iForPlr, int iPayPlr, object pToBase, bool fShowErrors);
global func id C4Id(string szID);
global func any Call(string szFunction, ...);
global func bool CanConcatPictureWith(object pOther);
global func int CastObjects(id id, int iNumber, int iLevel, int iX, int iY, int iAngle, int iAngleVariance);
global func bool CastParticles(string szName, int iAmount, int iLevel, int x, int y, int a0, int a1, int b0, int b1, object obj);
global func int CastPXS(string szMaterial, int iAmount, int iLevel, int x, int y, iAngle, iAngleVariance);
global func bool ChangeDef(id idNewDef);
global func bool ChangeEffect(string szEffectName, object pTarget, int iIndex, string szNewEffectName, int iNewTimer);
global func int CheckEffect(string szEffectName, object pTarget, int iPrio, int iTimerIntervall, var1, var2, var3, var4);
global func bool CheckEnergyNeedChain();
global func bool CheckVisibility(int player, object object);
global func int ClearMenuItems();
global func bool ClearParticles(string szName);
global func bool ClearScheduleCall(object obj, string szFunction);
global func bool CloseMenu();
global func bool Collect(object item);
global func bool ComponentAll(id idComponents);
global func object ComposeContents(id id);
global func any Construction(object creator);
global func object Contained();
global func object Contents(int iIndex);
global func int ContentsCount(id id);
global func int Cos(int iAngle, int iRadius, int iPrec);
global func array CreateArray(int Length);
global func object CreateConstruction(id id, int xOffset, int yOffset, int iOwner, int iCompletion, bool fTerrain, bool fCheckSite);
global func object CreateContents(id id, int iCount);
global func bool CreateMenu(id idSymbol, object pCommandObject, int iExtra, string szCaption, int iExtraData, int iStyle, bool fPermanent, id idMenuID);
global func object CreateObject(id id, int xOffset, int yOffset, int iOwner);
global func bool CreateParticle(string szName, int x, int y, int xDir, int yDir, int a, int b, object obj, bool fBehind);
global func bool CreateScriptPlayer(string szName, int dwClr, int idTeam, int dwFlags, id idExtraData);
global func bool CustomMessage(string message, object obj, int plr, int offset_x, int offset_y, int color, id deco, any portrait, int flags);
global func any DeathAnnounce();
global func any Definition(proplist def);
global func any DefinitionCall(id idDef, string szFunction, ...);
global func any DigFree(int x, int y, int iRadius);
global func any DigFreeRect(int x, int y, int iWdt, int iHgt);
global func any ClearFreeRect(int x, int y, int wdt, int hgt);
global func int Distance(int x1, int y1, int x2, int y2);
global func bool DoBreath(int iChange, object obj);
global func any DoCon(int iChange);
global func any DoCrewExp(int iChange);
global func any DoDamage(int iChange, int iDmgType, int iCausedBy);
global func any DoEnergy(int iChange, bool fExakt, int iEngType, int iCausedBy);
global func bool DoHomebaseMaterial(int player, id idID, int iChange);
global func bool DoHomebaseProduction(int player, id idID, int iChange);
global func bool DoMagicEnergy(int iChange, bool fAllowPartial);
global func int DoRGBaValue(int Val, int iChange, int iSelect);
global func bool DoScore(int player, int iChange);
global func bool DoScoreboardShow(int iChange, int iForPlr);
global func bool DoWealth(int player, int iValue);
global func bool DrawDefMap(int x, int y, int iWdt, int iHgt, string szMapDef);
global func bool DrawMap(int x, int y, int iWdt, int iHgt, string szMap);
global func bool DrawMaterialQuad(string szMaterialTexture, int x1, int y1, int x2, int y2, int x3, int y3, int x4, int y4, bool sub);
global func int DrawParticleLine(string szKind, int x0, int y0, int x1, int y1, int prtdist, int a, int b0, int b1, int yDir);
global func object EditCursor();
global func any EffectCall(object pTarget, proplist effect, string szCommand, ...);
global func bool EliminatePlayer(int player);
global func bool EnergyCheck(int iEnergy);
global func bool Enter(object pTarget);
global func any eval(string strScript);
global func bool Exit(int x, int y, int iR, int xDir, int yDir, int iRDir);
global func any Explode(int iLevel, id idEffect, string szParticle);
global func bool Extinguish();
global func int ExtractMaterialAmount(int x, int y, int iMat, int iAmount);
global func bool FightWith(object pTarget);
global func object FindBase(int player, int iIndex);
global func bool FindConstructionSite(id idDef, int iVarNumX, int iVarNumY);
global func object FindContents(id idType);
global func bool FindDefinition(id idDef);
global func object FindObject(array Criteria, ...);
global func array FindObjects(array Criteria, ...);
global func object FindOtherContents(id idType);
global func bool FinishCommand(bool fSuccess, int iCommandNum);
global func any Fling(int x_dir, int y_dir, int prec, bool add_speed);
global func string Format(string szStr, ...);
global func int FrameCounter();
global func any FreeRect(int x, int y, int iWdt, int iHgt, int iFreeDensity);
global func bool GainMissionAccess(string szPassword);
global func any GameCall(string szFunction, ...);
global func bool GameOver();
global func bool GBackLiquid(int x, int y);
global func bool GBackSemiSolid(int x, int y);
global func bool GBackSky(int x, int y);
global func bool GBackSolid(int x, int y);
global func string GetAction();
global func object GetActionTarget(int iTargetIndex);
global func int GetActTime();
global func bool GetAlive();
global func int GetBase();
global func bool GetBit(int iOldVal, int iBitNumber);
global func int GetBreath();
global func object GetCaptain(int player);
global func int GetCategory();
global func int GetChar(string szText, int iIndex);
global func int GetClimate();
global func int GetClrModulation(int iOverlayID);
global func int GetColor();
global func int GetComDir();
global func any GetCommand(int iElement, int iCommandNum);
global func any GetComponent(id idComponent, int iIndex, object obj, id idDef);
global func int GetCon();
global func int GetContact(int iVertex, int dwCNAT);
global func int GetController();
global func object GetCrew(int player, int iIndex);
global func int GetCrewCount(int player);
global func bool GetCrewEnabled();
global func any GetCrewExtraData(string strDataName);
global func object GetCursor(int player, int iIndex);
global func int GetDamage();
global func int GetDefBottom();
global func any GetDefCoreVal(string strEntry, string strSection, int iEntryNr);
global func id GetDefinition(int iIndex, int dwCategory);
global func string GetDesc();
global func int GetDir();
global func any GetEffect(string szEffectName, object pTarget, int iIndex, int iQueryVal, int iMaxPriority);
global func int GetEffectCount(string szMask, object pTarget, int iMaxPriority);
global func int GetEnergy();
global func bool GetEntrance();
global func int GetGravity();
global func object GetHiRank(int player);
global func int GetHomebaseMaterial(int player, id id, int iIndex, int dwCategory);
global func int GetHomebaseProduction(int player, id id, int iIndex, int dwCategory);
global func id GetID();
global func int GetKiller();
global func int GetLength(szText);
global func int GetMagicEnergy();
global func int GetMass();
global func int GetMaterial(int x, int y);
global func int GetMaterialCount(int iMaterial);
global func any GetMaterialVal(string strEntry, string strSection, int iMaterial, int iEntryNr);
global func any GetMenu();
global func any SetMenu(object menu_controller);
global func any GetMenuSelection();
global func bool GetMissionAccess(string strMissionAccess);
global func string GetName();
global func string GetNeededMatStr(object obj);
global func int GetObjectBlitMode(int iOverlayID);
global func any GetObjectInfoCoreVal(string strEntry, string strSection, int iEntryNr);
global func any GetObjectVal(string strEntry, string strSection, int iEntryNr);
global func int GetOCF();
global func int GetOwner();
global func int GetPathLength(int iFromX, int iFromY, int iToX, int iToY);
global func int GetPhase();
global func int GetPhysical(string szPhysical, int iMode);
global func int GetPlayerByIndex(int iIndex, int ePlayerType);
global func int GetPlayerByName(string szName);
global func int GetPlayerCount(int ePlayerType);
global func int GetPlayerID(int playerNumber);
global func any GetPlayerInfoCoreVal(string strEntry, string strSection, id iPlayer, int iEntryNr);
global func string GetPlayerName(int player);
global func int GetPlayerTeam(int player);
global func int GetPlayerType(int player);
global func any GetPlayerVal(string strEntry, string strSection, int player, int iEntryNr);
global func int GetPlayerColor(int player);
global func bool GetPlrDownDouble(int player);
global func any GetPlrExtraData(int player, string strDataName);
global func int GetPlrKnowledge(int player, id id, int iIndex, int dwCategory);
global func any GetPlrMagic(int player, id id, int iIndex);
global func int GetPlrValue(int player);
global func int GetPlrValueGain(int player);
global func object GetPlrView(int player);
global func int GetPlrViewMode(int player);
global func any GetPortrait(bool fGetID, bool fGetPermanent);
global func string GetProcedure();
global func any GetProperty(string key, proplist object);
global func int GetR();
global func int GetRank();
global func int GetRDir(int iPrecision);
global func int GetRGBaValue(int Val, int iSelect);
global func any GetScenarioVal(string strEntry, string strSection, int iEntryNr);
global func int GetScore(int player);
global func int GetSeason();
global func int GetSelectCount(int player);
global func int GetSkyAdjust(bool fBackColor);
global func int GetSkyColor(int iIndex, int iRGB);
global func int GetSystemTime(int iWhat);
global func string GetTaggedPlayerName(int player);
global func int GetTeamByIndex(int iIndex);
global func int GetTeamColor(int iTeam);
global func int GetTeamCount();
global func string GetTeamName(int iTeam);
global func int GetTemperature();
global func int GetTime();
global func int GetType(Value);
global func int GetUnusedOverlayID(int iBaseIndex);
global func int GetValue(object pBase, int iForPlayer);
global func int GetVertex(int iIndex, int data);
global func int GetVertexNum();
global func int GetWealth(int iOwner);
global func int GetWind(int x, int y, bool fGlobal);
global func int GetX(int precision);
global func int GetXDir(int iPrecision);
global func int GetY(int precision);
global func int GetYDir(int iPrecision);
global func any GlobalN(string szText);
global func bool GrabContents(object obj);
global func bool GrabObjectInfo(object pFrom);
global func bool Hostile(int player1, int player2, bool fCheckOneWayOnly);
global func int HSL(int byH, int byS, int byL);
global func int HSL2RGB(int Val);
global func int HSLa(int byH, int byS, int byL, int byA);
global func bool Incinerate();
global func any inherited();
global func bool InLiquid();
global func bool InsertMaterial(int iMat, int x, int y, int xDir, int yDir);
global func bool Inside(int iVal, int iRange1, int iRange2);
global func bool IsNetwork();
global func bool IsRef(Value);
global func bool Jump();
global func bool Kill(bool fForced);
global func int LandscapeHeight();
global func int LandscapeWidth();
global func bool LaunchEarthquake(int x, int y);
global func bool LaunchLightning(int x, int y, int xAdvance, int xRange, int yAdvance, int yRange, bool fDoGamma);
global func bool LaunchVolcano(int x, int y, int iStrength, string szMaterial);
global func any LocalN(string szName);
global func bool Log(string szMessage, ...);
global func bool MakeCrewMember(int player);
global func int Material(string szMaterialName);
global func string MaterialName(int iMat);
global func int Max(int iVal1, int iVal2);
global func bool Message(string strMessage, ...);
global func int Min(int iVal1, int iVal2);
global func int Music(string szSongName, bool fLoop);
global func int MusicLevel(int iLevel);
global func any NoContainer();
global func object Object(int iObj);
global func any ObjectCall(object obj, string szFunction, ...);
global func int ObjectCount(array Criteria, ...);
global func int ObjectDistance(object obj2, object obj);
global func int ObjectNumber();
global func bool OnFire();
global func any Par(int iIndex);
global func bool PathFree(int x1, int y1, int x2, int y2);
global func object PlaceAnimal(id id);
global func int PlaceObjects(id id, int iAmount, string Mat, int x, int y, int iWdt, int iHgt, bool fOnSurface, bool fNoStuck);
global func object PlaceVegetation(id id, int x, int y, int iWdt, int iHgt, int iGrowth);
global func bool PlayerMessage(int player, string szMessage, ...);
global func bool PlrMessage(string szMessage, int player, ...);
global func int Pow(int iVal1, int iVal2);
global func any PrivateCall(object obj, string szFunction, ...);
global func any ProtectedCall(object obj, string szFunction, ...);
global func bool Punch(object obj, int x);
global func bool PushParticles(string szName, int iAX, int iAY);
global func int Random(int iMaxVal);
global func int RandomX(int iVal1, int iVal2);
global func bool ReloadDef(id idDef);
global func bool ReloadParticle(string szParticle);
global func int RemoveAll(array Criteria, ...);
global func bool RemoveEffect(string szEffectName, object pTarget, proplist effect, bool fDoNoCalls, int iNewTimer);
global func any RemoveObject(bool fEjectContents);
global func int RemoveVertex(int x);
global func bool ResetGamma(int iRampIndex);
global func bool ResetPhysical(string sPhys);
global func bool Resort(object obj);
global func bool ResortObject(string szResortFunc);
global func bool ResortObjects(string szResortFunc, int iCategory);
global func any return(retval);
global func int RGB(int byR, int byG, int byB);
global func int RGB2HSL(int Val);
global func int RGBa(int byR, int byG, int byB, int byA);
global func bool Schedule(string szScript, int iInterval, int iRepeat, object obj);
global func bool ScheduleCall(object obj, string szFunction, int iInterval, int iRepeat);
global func int ScoreboardCol(id idDef);
global func object ScrollContents();
global func bool SelectCrew(int player, object obj, bool fSelect);
global func bool SelectMenuItem(int iItem);
global func any Sell(int player);
global func bool SetAction(string szAction, object pTarget1, object pTarget2);
global func bool SetActionData(int iData);
global func any SetActionTargets(object pTarget1, object pTarget2);
global func int SetAlive(bool fAlive);
global func int SetBit(int iOldVal, int iBitNumber, bool fBit);
global func bool SetBridgeActionData(int iBridgeLength, bool fMoveClonk, bool fWall, int iBridgeMaterial);
global func any SetCategory(int iCategory);
global func any SetClimate(int iClimate);
global func bool SetClrModulation(int dwClr, int iOverlayID);
global func any SetColor(int dwNewColor);
global func int SetComDir(int iComDir);
global func bool SetCommand(string szCommand, object pTarget, x, y, pTarget2, Data, int iRetries);
global func bool SetComponent(id idComponent, int iCount);
global func bool SetCon(int iCon);
global func bool SetContactDensity(int iDensity);
global func bool SetController(int iNewController);
global func any SetCrewEnabled(bool fEnabled);
global func any SetCrewExtraData(string strDataName, Data);
global func bool SetCrewStatus(int player, bool fInCrew);
global func bool SetCursor(int player, object obj, bool fNoSelectMark, bool fNoSelectArrow);
global func int SetDir(int iDir);
global func any SetEntrance(int iStatus);
global func int SetFilmView(int iToPlr);
global func any SetFoW(bool fEnabled, int player);
global func bool SetGameSpeed(int iGameSpeed);
global func bool SetGamma(int dwClr1, int dwClr2, int dwClr3, int iRampIndex);
global func bool SetGraphics(string szGfxName, id idSrcDef, int iOverlay, int iOverlayMode, string szAction, int dwBlitMode, object pOvelayObject);
global func any SetGravity(int iGravity);
global func bool SetHostility(int player1, int player2, bool fHostile, bool fSilent, bool fNoCalls);
global func bool SetLandscapePixel(int x, int y, int dwValue);
global func int SetLength(array aResize, int iSize);
global func any SetMass(int iNewMass);
global func bool SetMatAdjust(int dwClrMod);
global func bool SetMaxPlayer(int iNewCount);
global func bool SetMenuSize(int iCols, int iRows);
global func bool SetObjDrawTransform(int iWidth, int xSkew, int xAdjust, int ySkew, int iHeight, int yAdjust, int iOverlayID);
global func int SetObjectBlitMode(int dwNewBlitMod, int iOverlayID);
global func bool SetObjectOrder(object objBeforeOrAfter, object pSortObj, bool fAfter);
global func bool SetOwner(int iNewOwner);
global func bool SetPhase(int iPhase);
global func bool SetPhysical(string szPhysical, int iValue, int iMode);
global func any SetPicture(int x, int y, int iWdt, int iHgt);
global func int SetPlayerTeam(int player, int idNewTeam, bool fDoNoCalls);
global func int SetPlayList(string szPlayList);
global func any SetPlrExtraData(int player, string strDataName, Data);
global func int SetPlrKnowledge(int player, id idDef, bool fRemove);
global func int SetPlrMagic(int player, id id, bool Remove);
global func bool SetPlrShowCommand(int player, int iCom);
global func bool SetPlrShowControl(int player, string szDefString);
global func bool SetPlrShowControlPos(int player, int iPos);
global func bool SetPlrView(int player, object obj);
global func any SetPlrViewRange(int iRange);
global func bool SetPortrait(string szPortrait, id idSrcDef, bool fPermanent, bool fCopyGfx);
global func any SetPosition(int x, int y, bool fCheckBounds);
global func bool SetProperty(string key, value, proplist object);
global func bool SetR(int iR);
global func bool SetRDir(int iRDir, int iPrecision);
global func int SetRGBaValue(int Val, int iNewVal, int iSelect);
global func bool SetScoreboardData(int iRowID, int iColID, string sText, int iData);
global func any SetSeason(int iSeason);
global func any SetShape(int x, int y, int iWdt, int iHgt);
global func bool SetSkyAdjust(int dwClrMod, int dwBackClr);
global func bool SetSkyParallax(int iMode, int iParX, int iParY, int xDir, int yDir, int x, int y);
global func any SetSolidMask(int x, int y, int iWdt, int iHgt, int iTx, int iTx);
global func bool SetSpeed(int xDir, int yDir, object obj, int iPrecision);
global func any SetTemperature(int iTemperature);
global func bool SetTransferZone(int x, int y, int iWdt, int iHgt);
global func int SetVertex(int iIndex, int iValueToSet, int iValue, int iSetCustomPermanent);
global func bool SetVertexXY(int iIndex, int xPos, int yPos, object obj);
global func any SetViewOffset(int player, int x, int x);
global func bool SetVisibility(int dwVisibility, object obj);
global func bool SetWealth(int player, int iValue);
global func any SetWind(int iWind);
global func bool SetXDir(int xDir, int iPrecision);
global func bool SetYDir(int yDir, int iPrecision);
global func any ShakeFree(int x, int y, int iRadius);
global func any ShakeObjects(int x, int y, int iRadius);
global func bool ShiftContents(bool fShiftBack, id idTarget, bool fDoCalls);
global func bool ShowInfo(object object);
global func array SimFlight(int x, int y, int xspeed, int yspeed, int min_density, int max_density, int time, int precision);
global func int Sin(int iAngle, int iRadius, int iPrec);
global func int SkyPar_Keep();
global func bool Smoke(int x, int y, int iLevel);
global func bool SortScoreboard(int iColID, bool fReverse);
global func array Sort_Distance(int x, int y);
global func array Sort_Func(string strFunction);
global func array Sort_Mass();
global func array Sort_Multiple(array Criteria, ...);
global func array Sort_Random();
global func array Sort_Reverse(array iSort);
global func array Sort_Speed();
global func array Sort_Value();
global func bool Sound(string szSound, bool fGlobal, int iVolume, int player, int iLoopCount);
global func bool SplitRGBaValue(int Val, int iRed, int iGreen, int iBlue, int iAlpha);
global func int Sqrt(int iValue);
global func bool StartScriptProfiler(id idDefScript);
global func bool StopScriptProfiler();
global func bool Stuck();
global func int Tan(int iAngle, int iRadius, int iPrec);
global func object this();
global func int ToggleBit(int iOldVal, int iBitNumber);
global func bool TrainPhysical(string szPhysical, int iTrainBy, int iMaxTrain);
global func bool UnselectCrew(int player);
global func any VarN(string szName);
global func int VerticesStuck(object obj);
global func string WildcardMatch(string szStr, string szWildcard);
global func any _inherited(...);
global func any AsyncRandom();
global func bool SetKiller(int new_killer);
global func any SetName(string name, bool set_permanent, bool make_valid_if_exists);
global func proplist CreatePropList();
global func any ClearLastPlrCom();
global func string GetPlrControlName();
global func any SurrenderPlayer();
global func any SetLeaguePerformance(int score);
global func object GetViewCursor();
global func bool SetViewCursor(int player, object obj);
global func any GetTexture(int x, int y);
global func int GetAverageTextureColor(string texture);
global func any BlastObject(int level, int caused_by);
global func any BlastFree(int x, int y, int level, int caused_by);
global func any DrawVolcanoBranch();
global func any SetMenuDecoration();
global func any SetMenuTextProgress();
global func any GetLeague();
global func any TestMessageBoard();
global func any CallMessageBoard();
global func any AbortMessageBoard();
global func any OnMessageBoardAnswer();
global func any ActivateGameGoalMenu();
global func any CastBackParticles();
global func int GetMatAdjust();
global func object GetObjectLayer();
global func any SetObjectLayer(object new_layer);
global func any DrawMatChunks(int tx, int ty, int twdt, int thgt, int icntx, int icnty, string material, string texture, bool IFT);
global func any SetTextureIndex(string mat_tex, int new_index, bool insert);
global func any RemoveUnusedTexMapEntries();
global func any SetObjDrawTransform2();
global func any LoadScenarioSection();
global func any SetObjectStatus();
global func any GetObjectStatus();
global func any AdjustWalkRotation();
global func any FxFireStart();
global func any FxFireTimer();
global func any FxFireStop();
global func any FxFireInfo();
global func any ModulateColor();
global func any SetPreSend();
global func any GetTeamConfig();
global func any InitScenarioPlayer();
global func any GetScoreboardString();
global func any GetScoreboardData();
global func any AddEvaluationData(string text, int player);
global func any HideSettlementScoreInEvaluation(bool fHide);
global func any FatalError(string message);
global func any PlayVideo(string pFileName);
global func any StartCallTrace();
global func any PauseGame();
global func any ExecuteCommand();
global func any LocateFunc(string func_name, object obj, id def);
global func any SetNextMission(string next_mission, string next_mission_text, string next_mission_desc);
global func any IncinerateLandscape(int x, int y);
global func any Equal(a, b);
global func bool PlayerObjectCommand(parameters, ...);
global func array PathFree2(int x1, int y1, int x2, int y2);
global func any GameCallEx(string function_name, ...);
global func bool AddMessage(string message, ...);
global func bool DebugLog(string msg, ...);
global func int GetIndexOf(item, array array, ...);

global func string GetConstantNameByValue(int value, string name_prefix, int idx);

global func SetPlayerViewLock(int plr_idx, bool is_locked);
global func SetPlayerZoomByViewRange(int plr_idx, int range_wdt, int range_hgt, int flags);