static const C4D_All;
static const C4D_Background;
static const C4D_Goal;
static const C4D_Knowledge;
static const C4D_Living;
static const C4D_Object;
static const C4D_Parallax;
static const C4D_Rule;
static const C4D_StaticBack;
static const C4D_Structure;
static const C4D_Vehicle;
static const C4D_Environment;
static const C4D_SelectMaterial;
static const C4D_SelectHomebase;
static const C4D_SelectKnowledge;
static const C4D_SelectBuilding;
static const C4D_SelectInEarth;
static const C4D_SelectVehicle;
static const C4D_SelectAnimal;
static const C4V_Any;
static const C4V_Array;
static const C4V_Bool;
static const C4V_C4ID;
static const C4V_C4Object;
static const C4V_Int;
static const C4V_String;
static const COMD_Down;
static const COMD_DownLeft;
static const COMD_DownRight;
static const COMD_Left;
static const COMD_None;
static const COMD_Right;
static const COMD_Stop;
static const COMD_Up;
static const COMD_UpLeft;
static const COMD_UpRight;
static const DIR_Left;
static const DIR_Right;
static const NO_OWNER;
static const OCF_Alive;
static const OCF_AttractLightning;
static const OCF_Available;
static const OCF_Chop;
static const OCF_Collectible;
static const OCF_Collection;
static const OCF_Construct;
static const OCF_Container;
static const OCF_CrewMember;
static const OCF_Edible;
static const OCF_Entrance;
static const OCF_Exclusive;
static const OCF_FightReady;
static const OCF_Fullcon;
static const OCF_Grab;
static const OCF_HitSpeed1;
static const OCF_HitSpeed2;
static const OCF_HitSpeed3;
static const OCF_HitSpeed4;
static const OCF_Inflammable;
static const OCF_InFree;
static const OCF_InLiquid;
static const OCF_InSolid;
static const OCF_LineConstruct;
static const OCF_Living;
static const OCF_NotContained;
static const OCF_OnFire;
static const OCF_PowerConsumer;
static const OCF_PowerSupply;
static const OCF_Prey;
static const OCF_Rotate;
static const VIS_All;
static const VIS_Allies;
static const VIS_Enemies;
static const VIS_God;
static const VIS_Local;
static const VIS_None;
static const VIS_Owner;
static const C4D_Environment;
static const C4D_Magic;
static const C4D_MouseSelect;
static const C4D_Foreground;
static const C4D_MouseIgnore;
static const C4D_IgnoreFoW;
static const C4D_GrabGet;
static const C4D_GrabPut;
static const C4D_LinePower;
static const C4D_LineSource;
static const C4D_LineDrain;
static const C4D_LineLightning;
static const C4D_LineVolcano;
static const C4D_LineRope;
static const C4D_LineColored;
static const C4D_LineVertex;
static const C4D_PowerInput;
static const C4D_PowerOutput;
static const C4D_LiquidInput;
static const C4D_LiquidOutput;
static const C4D_PowerGenerator;
static const C4D_PowerConsumer;
static const C4D_LiquidPump;
static const C4D_EnergyHolder;
static const C4V_PropList;
static const CON_CursorLeft;
static const CON_CursorToggle;
static const CON_CursorRight;
static const CON_Throw;
static const CON_Up;
static const CON_Dig;
static const CON_Left;
static const CON_Down;
static const CON_Right;
static const CON_Menu;
static const CON_Special;
static const CON_Special2;
static const VIS_Select;
static const VIS_LayerToggle;
static const VIS_OverlayOnly;
static const C4X_Ver1;
static const C4X_Ver2;
static const C4X_Ver3;
static const C4X_Ver4;
static const C4X_VerBuild;
static const SkyPar_Keep;
static const C4MN_Style_Normal;
static const C4MN_Style_Context;
static const C4MN_Style_Info;
static const C4MN_Style_Dialog;
static const C4MN_Style_EqualItemHeight;
static const C4MN_Extra_None;
static const C4MN_Extra_Components;
static const C4MN_Extra_Value;
static const C4MN_Extra_MagicValue;
static const C4MN_Extra_Info;
static const C4MN_Extra_ComponentsMagic;
static const C4MN_Extra_LiveMagicValue;
static const C4MN_Extra_ComponentsLiveMagic;
static const C4MN_Add_ImgRank;
static const C4MN_Add_ImgIndexed;
static const C4MN_Add_ImgObjRank;
static const C4MN_Add_ImgObject;
static const C4MN_Add_ImgTextSpec;
static const C4MN_Add_ImgColor;
static const C4MN_Add_PassValue;
static const C4MN_Add_ForceCount;
static const C4MN_Add_ForceNoDesc;
static const FX_OK;
static const FX_Effect_Deny;
static const FX_Effect_Annul;
static const FX_Effect_AnnulDoCalls;
static const FX_Execute_Kill;
static const FX_Stop_Deny;
static const FX_Start_Deny;
static const FX_Call_Normal;
static const FX_Call_Temp;
static const FX_Call_TempAddForRemoval;
static const FX_Call_RemoveClear;
static const FX_Call_RemoveDeath;
static const FX_Call_DmgScript;
static const FX_Call_DmgBlast;
static const FX_Call_DmgFire;
static const FX_Call_DmgChop;
static const FX_Call_Energy;
static const FX_Call_EngScript;
static const FX_Call_EngBlast;
static const FX_Call_EngObjHit;
static const FX_Call_EngFire;
static const FX_Call_EngBaseRefresh;
static const FX_Call_EngAsphyxiation;
static const FX_Call_EngCorrosion;
static const FX_Call_EngStruct;
static const FX_Call_EngGetPunched;
static const GFXOV_MODE_None;
static const GFXOV_MODE_Base;
static const GFXOV_MODE_Action;
static const GFXOV_MODE_Picture;
static const GFXOV_MODE_IngamePicture;
static const GFXOV_MODE_Object;
static const GFXOV_MODE_ExtraGraphics;
static const GFX_Overlay;
static const GFXOV_Clothing;
static const GFXOV_Tools;
static const GFXOV_ProcessTarget;
static const GFXOV_Misc;
static const GFXOV_UI;
static const GFX_BLIT_Additive;
static const GFX_BLIT_Mod2;
static const GFX_BLIT_ClrSfc_OwnClr;
static const GFX_BLIT_ClrSfc_Mod2;
static const GFX_BLIT_Custom;
static const GFX_BLIT_Parent;
static const CNAT_None;
static const CNAT_Left;
static const CNAT_Right;
static const CNAT_Top;
static const CNAT_Bottom;
static const CNAT_Center;
static const CNAT_MultiAttach;
static const CNAT_NoCollision;
static const VTX_X;
static const VTX_Y;
static const VTX_CNAT;
static const VTX_Friction;
static const VTX_SetPermanent;
static const VTX_SetPermanentUpd;
static const C4M_Vehicle;
static const C4M_Solid;
static const C4M_SemiSolid;
static const C4M_Liquid;
static const C4M_Background;
static const SBRD_Caption;
static const TEAM_Custom;
static const TEAM_Active;
static const TEAM_AllowHostilityChange;
static const TEAM_Dist;
static const TEAM_AllowTeamSwitch;
static const TEAM_AutoGenerateTeams;
static const TEAM_TeamColors;
static const C4OS_DELETED;
static const C4OS_NORMAL;
static const C4OS_INACTIVE;
static const C4MSGCMDR_Escaped;
static const C4MSGCMDR_Plain;
static const C4MSGCMDR_Identifier;
static const C4FO_Not;
static const C4FO_And;
static const C4FO_Or;
static const C4FO_Exclude;
static const C4FO_InRect;
static const C4FO_AtPoint;
static const C4FO_AtRect;
static const C4FO_OnLine;
static const C4FO_Distance;
static const C4FO_ID;
static const C4FO_OCF;
static const C4FO_Category;
static const C4FO_Action;
static const C4FO_ActionTarget;
static const C4FO_Container;
static const C4FO_AnyContainer;
static const C4FO_Owner;
static const C4FO_Controller;
static const C4FO_Func;
static const C4FO_Layer;
static const C4SO_Reverse;
static const C4SO_Multiple;
static const C4SO_Distance;
static const C4SO_Random;
static const C4SO_Speed;
static const C4SO_Mass;
static const C4SO_Value;
static const C4SO_Func;
static const PHYS_Current;
static const PHYS_Permanent;
static const PHYS_Temporary;
static const PHYS_StackTemporary;
static const C4CMD_Base;
static const C4CMD_SilentBase;
static const C4CMD_Sub;
static const C4CMD_SilentSub;
static const C4CMD_MoveTo_NoPosAdjust;
static const C4CMD_MoveTo_PushTarget;
static const C4CMD_Enter_PushTarget;
static const C4SECT_SaveLandscape;
static const C4SECT_SaveObjects;
static const C4SECT_KeepEffects;
static const TEAMID_New;
static const MSG_NoLinebreak;
static const MSG_Bottom;
static const MSG_Multiple;
static const MSG_Top;
static const MSG_Left;
static const MSG_Right;
static const MSG_HCenter;
static const MSG_VCenter;
static const MSG_DropSpeech;
static const MSG_WidthRel;
static const MSG_XRel;
static const MSG_YRel;
static const C4PT_User;
static const C4PT_Script;
static const CSPF_FixedAttributes;
static const CSPF_NoScenarioInit;
static const CSPF_NoEliminationCheck;
static const CSPF_Invisible;
static const any nil;

static const ANIM_Hold;
static const ANIM_Loop;
static const ANIM_Remove;

static const C4AVP_Const;
static const C4AVP_Linear;
static const C4AVP_X;
static const C4AVP_Y;
static const C4AVP_AbsX;
static const C4AVP_AbsY;
static const C4AVP_XDir;
static const C4AVP_YDir;
static const C4AVP_RDir;
static const C4AVP_CosR;
static const C4AVP_SinR;
static const C4AVP_CosV;
static const C4AVP_SinV;
static const C4AVP_Action;

static const C4FO_Not;
static const C4FO_And;
static const C4FO_Or;
static const C4FO_Exclude;
static const C4FO_InRect;
static const C4FO_AtPoint;
static const C4FO_AtRect;
static const C4FO_OnLine;
static const C4FO_Distance;
static const C4FO_ID;
static const C4FO_OCF;
static const C4FO_Category;
static const C4FO_Action;
static const C4FO_ActionTarget;
static const C4FO_Procedure;
static const C4FO_Container;
static const C4FO_AnyContainer;
static const C4FO_Owner;
static const C4FO_Controller;
static const C4FO_Func;
static const C4FO_Layer;

static const C4SO_Reverse;
static const C4SO_Multiple;
static const C4SO_Distance;
static const C4SO_Random;
static const C4SO_Speed;
static const C4SO_Mass;
static const C4SO_Value;
static const C4SO_Func;

static const PHYS_Current;
static const PHYS_Permanent;
static const PHYS_Temporary;
static const PHYS_StackTemporary;

static const C4CMD_Base;
static const C4CMD_SilentBase;
static const C4CMD_Sub;
static const C4CMD_SilentSub;

static const C4CMD_MoveTo_NoPosAdjust;
static const C4CMD_MoveTo_PushTarget;
static const C4CMD_Enter_PushTarget;

static const C4SECT_SaveLandscape;
static const C4SECT_SaveObjects;
static const C4SECT_KeepEffects;

static const TEAMID_New;

static const MSG_NoLinebreak;
static const MSG_Bottom;
static const MSG_Multiple;
static const MSG_Top;
static const MSG_Left;
static const MSG_Right;
static const MSG_HCenter;
static const MSG_VCenter;
static const MSG_DropSpeech;
static const MSG_WidthRel;
static const MSG_XRel;
static const MSG_YRel;

static const C4PT_User;
static const C4PT_Script;

static const CSPF_FixedAttributes;
static const CSPF_NoScenarioInit;
static const CSPF_NoEliminationCheck;
static const CSPF_Invisible;

static const GFXOV_MODE_None;
static const GFXOV_MODE_Base;
static const GFXOV_MODE_Action;
static const GFXOV_MODE_Picture;
static const GFXOV_MODE_IngamePicture;
static const GFXOV_MODE_Object;
static const GFXOV_MODE_ExtraGraphics;
static const GFXOV_MODE_Rank;
static const GFXOV_MODE_ObjectPicture;

static const DMQ_Sky;
static const DMQ_Sub;
static const DMQ_Bridge;

global func int AttachMesh(mesh, string szParentBone, string szChildBone, array Transformation);
global func int GetAnimationLength();
global func string GetAnimationName();
global func int PlayAnimation(string szAnimation, int iSlot, array PositionProvider, array WeightProvider, int iSibling, int iAttachNumber);
global func int GetAnimationPosition(int iAnimationNumber, int iAttachNumber);
global func int GetAnimationWeight(int iAnimationNumber, int iAttachNumber);
global func int GetPlayerControlState(int iPlr, int iControl);
global func int GetRootAnimation(int iSlot, int iAttachNumber);
global func bool SetAnimationPosition(int iAnimationNumber, array PositionProvider, int iAttachNumber);
global func bool SetAnimationWeight(int iAnimationNumber, array WeightProvider, int iAttachNumber);
global func bool SetPlayerControlEnabled(int iPlr, int ctrl, bool is_enabled);
global func bool StopAnimation(int iAnimationNumber, int iAttachNumber);
global func bool DetachMesh(int iAttachNumber);

global func ResetCursorView(int plr);
global func string Translate(string text);

global func int Abs(int iValue);
global func int AbsX(int iX);
global func int AbsY(int iY);
global func bool ActIdle();
global func bool Activate(object obj);
global func bool AddCommand(string szCommand, object pTarget, int iX, int iY, object pTarget2, int iInterval, Data, int iRetries, int iBaseMode);
global func int AddEffect(string szEffectName, object pTarget, int iPrio, int iTimerIntervall, object pCmdTarget, idCmdTarget, var1, var2, var3, var4);
global func int AddMenuItem(string szCaption, string szCommand, id idItem, int iCount, iParameter, string szInfoCaption, int iExtra, XPar1, XPar2);
global func int AddMsgBoardCmd(string strCommand, string strScript);
global func int AddVertex(int iX, int iY);
global func int Angle(int iX1, int iY1, int iX2, int iY2, int iPrec);
global func int AnyContainer();
global func bool AppendCommand(string szCommand, object pTarget, int iX, int iY, object pTarget2, int iInterval, Data, int iRetries, int iBaseMode);
global func int ArcCos(int iVal, int iRadius);
global func int ArcSin(int iVal, int iRadius);
global func int BlastObjects(int iX, int iY, int iLevel, object pContainer, int iCausedBy);
global func int BoundBy(int iVal, int iRange1, int iRange2);
global func bool Bubble(int iX, int iY);
global func object Buy(id idBuyObj, int iForPlr, int iPayPlr, object pToBase, bool fShowErrors);
global func id C4Id(string szID);
global func any Call(string szFunction);
global func bool CanConcatPictureWith(object pOther);
global func int CastObjects(id, iNumber, iLevel, iX, iY, iAngle, iAngleVariance);
global func bool CastParticles(string szName, int iAmount, int iLevel, int iX, int iY, int a0, int a1, int b0, int b1, object pObj);
global func int CastPXS(string szMaterial, int iAmount, int iLevel, int iX, int iY, iAngle, iAngleVariance);
global func bool ChangeDef(id idNewDef);
global func bool ChangeEffect(string szEffectName, object pTarget, int iIndex, string szNewEffectName, int iNewTimer);
global func int CheckEffect(string szEffectName, object pTarget, int iPrio, int iTimerIntervall, var1, var2, var3, var4);
global func bool CheckEnergyNeedChain();
global func bool CheckVisibility(int iPlayer, object pObject);
global func int ClearMenuItems();
global func bool ClearParticles(string szName);
global func bool ClearScheduleCall(object pObj, string szFunction);
global func bool CloseMenu();
global func bool Collect(object pItem, object pTarget);
global func bool ComponentAll(id idComponents);
global func object ComposeContents(id id);
global func any Construction(object creator);
global func object Contained();
global func object Contents(int iIndex);
global func int ContentsCount(id id);
global func int Cos(int iAngle, int iRadius, int iPrec);
global func array CreateArray(int Length);
global func object CreateConstruction(id id, int iXOffset, int iYOffset, int iOwner, int iCompletion, bool fTerrain, bool fCheckSite);
global func object CreateContents(id id, int iCount);
global func bool CreateMenu(id idSymbol, object pCommandObject, int iExtra, string szCaption, int iExtraData, int iStyle, bool fPermanent, id idMenuID);
global func object CreateObject(id id, int iXOffset, int iYOffset, int iOwner);
global func bool CreateParticle(string szName, int iX, int iY, int iXDir, int iYDir, int a, int b, object pObj, bool fBehind);
global func bool CreateScriptPlayer(string szName, int dwClr, int idTeam, int dwFlags, id idExtraData);
global func bool CustomMessage(string message, object obj, int plr, int offset_x, int offset_y, int color, id deco, string portrait, int flags);
global func any DeathAnnounce();
global func any Definition(proplist def);
global func any DefinitionCall(id idDef, string szFunction);
global func any DigFree(int iX, int iY, int iRadius);
global func any DigFreeRect(int iX, int iY, int iWdt, int iHgt);
global func int Distance(int iX1, int iY1, int iX2, int iY2);
global func bool DoBreath(int iChange, object pObj);
global func any DoCon(int iChange);
global func any DoCrewExp(int iChange);
global func any DoDamage(int iChange, int iDmgType, int iCausedBy);
global func any DoEnergy(int iChange, bool fExakt, int iEngType, int iCausedBy);
global func bool DoHomebaseMaterial(int iPlr, id idID, int iChange);
global func bool DoHomebaseProduction(int iPlr, id idID, int iChange);
global func bool DoMagicEnergy(int iChange, bool fAllowPartial);
global func int DoRGBaValue(int Val, int iChange, int iSelect);
global func bool DoScore(int iPlr, int iChange);
global func bool DoScoreboardShow(int iChange, int iForPlr);
global func bool DoWealth(int iPlr, int iValue);
global func bool DrawDefMap(int iX, int iY, int iWdt, int iHgt, string szMapDef);
global func bool DrawMap(int iX, int iY, int iWdt, int iHgt, string szMap);
global func bool DrawMaterialQuad(string szMaterialTexture, int iX1, int iY1, int iX2, int iY2, int iX3, int iY3, int iX4, int iY4, bool sub);
global func int DrawParticleLine(string szKind, int x0, int y0, int x1, int y1, int prtdist, int a, int b0, int b1, int iYDir);
global func object EditCursor();
global func any EffectCall(object pTarget, int iNumber, string szCommand);
global func & EffectVar(int iVarIndex, object pTarget, int iNumber);
global func bool EliminatePlayer(int iPlr);
global func bool EnergyCheck(int iEnergy);
global func bool Enter(object pTarget);
global func any eval(string strScript);
global func bool Exit(int iX, int iY, int iR, int iXDir, int iYDir, int iRDir);
global func any Explode(int iLevel, id idEffect, string szParticle);
global func bool Extinguish();
global func int ExtractLiquid(int iX, int iY);
global func int ExtractMaterialAmount(int iX, int iY, int iMat, int iAmount);
global func bool FightWith(object pTarget);
global func object FindBase(int iPlr, int iIndex);
global func bool FindConstructionSite(id idDef, int iVarNumX, int iVarNumY);
global func object FindContents(id idType);
global func bool FindDefinition(id idDef);
global func object FindObject(array Criteria);
global func array FindObjects(array Criteria);
global func object FindOtherContents(id idType);
global func array Find_Action(string szAction);
global func array Find_ActionTarget(object pActionTarget);
global func array Find_Allied(int iPlr);
global func array Find_And(array Criteria);
global func array Find_AnyContainer();
global func array Find_AtPoint(int iX, int iY);
global func array Find_Category(int iCategory);
global func array Find_Container(object pContainer);
global func array Find_Distance(int iRadius, int iX, int iY);
global func array Find_Exclude(object pExclude);
global func array Find_Func(string strFunction);
global func array Find_Hostile(int iPlr);
global func array Find_ID(id idDef);
global func array Find_InRect(int iX, int iY, int iWdt, int iHgt);
global func array Find_NoContainer();
global func array Find_Not(array Criteria);
global func array Find_OCF(int iOCF);
global func array Find_Or(array Criteria);
global func array Find_Owner(int iPlr);
global func bool FinishCommand(bool fSuccess, int iCommandNum);
global func any Fling(int iXDir, int iYDir);
global func string Format(string szStr);
global func int FrameCounter();
global func any FreeRect(int iX, int iY, int iWdt, int iHgt, int iFreeDensity);
global func bool GainMissionAccess(string szPassword);
global func any GameCall(string szFunction);
global func bool GameOver();
global func bool GBackLiquid(int iX, int iY);
global func bool GBackSemiSolid(int iX, int iY);
global func bool GBackSky(int iX, int iY);
global func bool GBackSolid(int iX, int iY);
global func string GetAction();
global func object GetActionTarget(int iTargetIndex);
global func any GetActMapVal(string strEntry, string strAction, id idDef, int iEntryNr);
global func int GetActTime();
global func bool GetAlive();
global func int GetBase();
global func bool GetBit(int iOldVal, int iBitNumber);
global func int GetBreath();
global func object GetCaptain(int iPlayer);
global func int GetCategory();
global func int GetChar(string szText, int iIndex);
global func int GetClimate();
global func int GetClrModulation(int iOverlayID);
global func int GetColor();
global func int GetComDir();
global func any GetCommand(int iElement, int iCommandNum);
global func any GetComponent(id idComponent, int iIndex, object pObj, id idDef);
global func int GetCon();
global func int GetContact(int iVertex, int dwCNAT);
global func int GetController();
global func object GetCrew(int iPlayer, int iIndex);
global func int GetCrewCount(int iPlayer);
global func bool GetCrewEnabled();
global func any GetCrewExtraData(object pCrew, string strDataName);
global func object GetCursor(int iPlayer, int iIndex);
global func int GetDamage();
global func int GetDefBottom();
global func any GetDefCoreVal(string strEntry, string strSection, int iEntryNr);
global func id GetDefinition(int iIndex, int dwCategory);
global func string GetDesc();
global func int GetDir();
global func any GetEffect(string szEffectName, object pTarget, int iIndex, int iQueryVal, int iMaxPriority);
global func int GetEffectCount(string szMask, object pTarget, int iMaxPriority);
global func int GetEnergy();
global func bool GetEntrance();
global func int GetGravity();
global func object GetHiRank(int iPlayer);
global func int GetHomebaseMaterial(int iPlr, id id, int iIndex, int dwCategory);
global func int GetHomebaseProduction(int iPlr, id id, int iIndex, int dwCategory);
global func id GetID();
global func int GetKiller();
global func int GetLength(szText);
global func int GetMagicEnergy();
global func int GetMass();
global func int GetMaterial(int iX, int iY);
global func int GetMaterialCount(int iMaterial);
global func any GetMaterialVal(string strEntry, string strSection, int iMaterial, int iEntryNr);
global func any GetMenu();
global func any GetMenuSelection();
global func bool GetMissionAccess(string strMissionAccess);
global func string GetName();
global func string GetNeededMatStr(object pObj);
global func int GetObjectBlitMode(int iOverlayID);
global func any GetObjectInfoCoreVal(string strEntry, string strSection, int iEntryNr);
global func any GetObjectVal(string strEntry, string strSection, int iEntryNr);
global func int GetOCF();
global func int GetOwner();
global func int GetPathLength(int iFromX, int iFromY, int iToX, int iToY);
global func int GetPhase();
global func int GetPhysical(string szPhysical, int iMode);
global func int GetPlayerByIndex(int iIndex, int ePlayerType);
global func int GetPlayerByName(string szName);
global func int GetPlayerCount(int ePlayerType);
global func int GetPlayerID(int iPlayerNumber);
global func any GetPlayerInfoCoreVal(string strEntry, string strSection, id iPlayer, int iEntryNr);
global func string GetPlayerName(int iPlayer);
global func int GetPlayerTeam(int iPlr);
global func int GetPlayerType(int iPlayer);
global func any GetPlayerVal(string strEntry, string strSection, int iPlayer, int iEntryNr);
global func int GetPlrColor(int iPlr);
global func bool GetPlrDownDouble(int iPlr);
global func any GetPlrExtraData(int iPlr, string strDataName);
global func int GetPlrKnowledge(int iPlr, id id, int iIndex, int dwCategory);
global func any GetPlrMagic(int iPlr, id id, int iIndex);
global func int GetPlrValue(int iPlr);
global func int GetPlrValueGain(int iPlr);
global func object GetPlrView(int iPlr);
global func int GetPlrViewMode(int iPlr);
global func any GetPortrait(bool fGetID, bool fGetPermanent);
global func string GetProcedure();
global func any GetProperty(string key, proplist object);
global func int GetR();
global func int GetRank();
global func int GetRDir(int iPrecision);
global func int GetRGBaValue(int Val, int iSelect);
global func any GetScenarioVal(string strEntry, string strSection, int iEntryNr);
global func int GetScore(int iPlayer);
global func int GetSeason();
global func int GetSelectCount(int iPlayer);
global func int GetSkyAdjust(bool fBackColor);
global func int GetSkyColor(int iIndex, int iRGB);
global func int GetSystemTime(int iWhat);
global func string GetTaggedPlayerName(int iPlayer);
global func int GetTeamByIndex(int iIndex);
global func int GetTeamColor(int iTeam);
global func int GetTeamCount();
global func string GetTeamName(int iTeam);
global func int GetTemperature();
global func int GetTime();
global func int GetType(Value);
global func int GetUnusedOverlayID(int iBaseIndex);
global func int GetValue(object pBase, int iForPlayer);
global func int GetVertex(int iIndex, int data);
global func int GetVertexNum();
global func bool CheckVisibility(int iPlayer, object pObject);
global func int GetWealth(int iOwner);
global func int GetWind(int iX, int iY, bool fGlobal);
global func int GetX();
global func int GetXDir(int iPrecision);
global func int GetY();
global func int GetYDir(int iPrecision);
global func & GlobalN(string szText);
global func any goto(int iCounter);
global func bool GrabContents(object pObj);
global func bool GrabObjectInfo(object pFrom);
global func bool Hostile(int iPlr1, int iPlr2, bool fCheckOneWayOnly);
global func int HSL(int byH, int byS, int byL);
global func int HSL2RGB(int Val);
global func int HSLa(int byH, int byS, int byL, int byA);
global func bool Incinerate();
global func any inherited();
global func bool InLiquid();
global func bool InsertMaterial(int iMat, int iX, int iY, int iXDir, int iYDir);
global func bool Inside(int iVal, int iRange1, int iRange2);
global func bool IsNetwork();
global func bool IsRef(Value);
global func bool Jump();
global func bool Kill(bool fForced);
global func int LandscapeHeight();
global func int LandscapeWidth();
global func bool LaunchEarthquake(int iX, int iY);
global func bool LaunchLightning(int iX, int iY, int iXAdvance, int iXRange, int iYAdvance, int iYRange, bool fDoGamma);
global func bool LaunchVolcano(int iX, int iY, int iStrength, string szMaterial);
global func & LocalN(string szName);
global func bool Log(string szMessage);
global func bool MakeCrewMember(int iPlayer);
global func int Material(string szMaterialName);
global func string MaterialName(int iMat);
global func int Max(int iVal1, int iVal2);
global func bool Message(string strMessage, object pObj);
global func int Min(int iVal1, int iVal2);
global func int Music(string szSongName, bool fLoop);
global func int MusicLevel(int iLevel);
global func int NoContainer();
global func object Object(int iObj);
global func any ObjectCall(object pObj, string szFunction);
global func int ObjectCount(array Criteria);
global func int ObjectDistance(object pObj2, object pObj);
global func int ObjectNumber();
global func bool OnFire();
global func any Par(int iIndex);
global func bool PathFree(int iX1, int iY1, int iX2, int iY2);
global func object PlaceAnimal(id id);
global func int PlaceObjects(id, int iAmount, string Mat, int iX, int iY, int iWdt, int iHgt, bool fOnSurface, bool fNoStuck);
global func object PlaceVegetation(id id, int iX, int iY, int iWdt, int iHgt, int iGrowth);
global func bool PlayerMessage(int iPlr, string szMessage, object pObj);
global func bool PlrMessage(string szMessage, int iPlr);
global func int Pow(int iVal1, int iVal2);
global func any PrivateCall(object pObj, string szFunction);
global func any ProtectedCall(object pObj, string szFunction);
global func bool Punch(object pObj, int iX);
global func bool PushParticles(string szName, int iAX, int iAY);
global func int Random(int iMaxVal);
global func int RandomX(int iVal1, int iVal2);
global func bool ReloadDef(id idDef);
global func bool ReloadParticle(string szParticle);
global func int RemoveAll(array Criteria);
global func bool RemoveEffect(string szEffectName, object pTarget, int iIndex, bool fDoNoCalls, int iNewTimer);
global func any RemoveObject(bool fEjectContents);
global func int RemoveVertex(int iX);
global func bool ResetGamma(int iRampIndex);
global func bool ResetPhysical(string sPhys);
global func bool Resort(object pObj);
global func bool ResortObject(string szResortFunc);
global func bool ResortObjects(string szResortFunc, int iCategory);
global func any return(retval);
global func int RGB(int byR, int byG, int byB);
global func int RGB2HSL(int Val);
global func int RGBa(int byR, int byG, int byB, int byA);
global func bool Schedule(string szScript, int iInterval, int iRepeat, object pObj);
global func bool ScheduleCall(object pObj, string szFunction, int iInterval, int iRepeat);
global func int ScoreboardCol(id idDef);
global func int ScriptCounter();
global func bool ScriptGo(bool fStart);
global func object ScrollContents();
global func bool SelectCrew(int iPlr, object pObj, bool fSelect);
global func bool SelectMenuItem(int iItem);
global func any Sell(int iPlr);
global func bool SetAction(string szAction, object pTarget1, object pTarget2);
global func bool SetActionData(int iData);
global func any SetActionTargets(object pTarget1, object pTarget2);
global func int SetAlive(bool fAlive);
global func int SetBit(int iOldVal, int iBitNumber, bool fBit);
global func bool SetBridgeActionData(int iBridgeLength, bool fMoveClonk, bool fWall, int iBridgeMaterial);
global func any SetCategory(int iCategory);
global func any SetClimate(int iClimate);
global func bool SetClrModulation(int dwClr, int iOverlayID);
global func any SetColor(int dwNewColor);
global func int SetComDir(int iComDir);
global func bool SetCommand(string szCommand, object pTarget, int iX, int iY, object pTarget2, Data, int iRetries);
global func bool SetComponent(id idComponent, int iCount);
global func bool SetCon(int iCon);
global func bool SetContactDensity(int iDensity);
global func bool SetController(int iNewController);
global func any SetCrewEnabled(bool fEnabled);
global func any SetCrewExtraData(string strDataName, Data);
global func bool SetCrewStatus(int iPlr, bool fInCrew);
global func bool SetCursor(int iPlr, object pObj, bool fNoSelectMark, bool fNoSelectArrow);
global func int SetDir(int iDir);
global func any SetEntrance(int iStatus);
global func int SetFilmView(int iToPlr);
global func any SetFoW(bool fEnabled, int iPlayer);
global func bool SetGameSpeed(int iGameSpeed);
global func bool SetGamma(int dwClr1, int dwClr2, int dwClr3, int iRampIndex);
global func bool SetGraphics(string szGfxName, id idSrcDef, int iOverlay, int iOverlayMode, string szAction, int dwBlitMode, object pOvelayObject);
global func any SetGravity(int iGravity);
global func bool SetHostility(int iPlr1, int iPlr2, bool fHostile, bool fSilent, bool fNoCalls);
global func bool SetLandscapePixel(int iX, int iY, int dwValue);
global func int SetLength(array aResize, int iSize);
global func any SetMass(int iNewMass);
global func bool SetMatAdjust(int dwClrMod);
global func bool SetMaxPlayer(int iNewCount);
global func bool SetMenuSize(int iCols, int iRows);
global func bool SetObjDrawTransform(int iWidth, int iXSkew, int iXAdjust, int iYSkew, int iHeight, int iYAdjust, int iOverlayID);
global func int SetObjectBlitMode(int dwNewBlitMod, int iOverlayID);
global func bool SetObjectOrder(object pObjBeforeOrAfter, object pSortObj, bool fAfter);
global func bool SetOwner(int iNewOwner);
global func bool SetPhase(int iPhase);
global func bool SetPhysical(string szPhysical, int iValue, int iMode);
global func any SetPicture(int iX, int iY, int iWdt, int iHgt);
global func int SetPlayerTeam(int iPlr, int idNewTeam, bool fDoNoCalls);
global func int SetPlayList(string szPlayList);
global func any SetPlrExtraData(int iPlr, string strDataName, Data);
global func int SetPlrKnowledge(int iPlr, id idDef, bool fRemove);
global func int SetPlrMagic(int iPlr, id id, bool Remove);
global func bool SetPlrShowCommand(int iPlr, int iCom);
global func bool SetPlrShowControl(int iPlr, string szDefString);
global func bool SetPlrShowControlPos(int iPlr, int iPos);
global func bool SetPlrView(int iPlr, object pObj);
global func any SetPlrViewRange(int iRange);
global func bool SetPortrait(string szPortrait, id idSrcDef, bool fPermanent, bool fCopyGfx);
global func any SetPosition(int iX, int iY, bool fCheckBounds);
global func bool SetProperty(string key, value, proplist object);
global func bool SetR(int iR);
global func bool SetRDir(int iRDir, int iPrecision);
global func int SetRGBaValue(int Val, int iNewVal, int iSelect);
global func bool SetScoreboardData(int iRowID, int iColID, string sText, int iData);
global func any SetSeason(int iSeason);
global func any SetShape(int iX, int iY, int iWdt, int iHgt);
global func bool SetSkyAdjust(int dwClrMod, int dwBackClr);
global func bool SetSkyParallax(int iMode, int iParX, int iParY, int iXDir, int iYDir, int iX, int iY);
global func any SetSolidMask(int iX, int iY, int iWdt, int iHgt, int iTx, int iTx);
global func bool SetSpeed(int iXDir, int iYDir, object pObj, int iPrecision);
global func any SetTemperature(int iTemperature);
global func bool SetTransferZone(int iX, int iY, int iWdt, int iHgt);
global func int SetVertex(int iIndex, int iValueToSet, int iValue, int iSetCustomPermanent);
global func bool SetVertexXY(int iIndex, int iXPos, int iYPos, object pObj);
global func any SetViewOffset(int iPlayer, int iX, int iX);
global func bool SetVisibility(int dwVisibility, object pObj);
global func bool SetWealth(int iPlr, int iValue);
global func any SetWind(int iWind);
global func bool SetXDir(int iXDir, int iPrecision);
global func bool SetYDir(int iYDir, int iPrecision);
global func any ShakeFree(int iX, int iY, int iRadius);
global func any ShakeObjects(int iX, int iY, int iRadius);
global func bool ShiftContents(bool fShiftBack, id idTarget, bool fDoCalls);
global func bool ShowInfo(object pObject);
global func bool SimFlight(iX, iY, iXDir, iYDir, int iMinDensity, int iMaxDensity, int iIteration, int iPrecision);
global func int Sin(int iAngle, int iRadius, int iPrec);
global func int SkyPar_Keep();
global func bool Smoke(int iX, int iY, int iLevel);
global func bool SortScoreboard(int iColID, bool fReverse);
global func array Sort_Distance(int iX, int iY);
global func array Sort_Func(string strFunction);
global func array Sort_Mass();
global func array Sort_Multiple(array Criteria);
global func array Sort_Random();
global func array Sort_Reverse(array iSort);
global func array Sort_Speed();
global func array Sort_Value();
global func bool Sound(string szSound, bool fGlobal, int iVolume, int iPlayer, int iLoopCount);
global func bool Split2Components(object pObj);
global func bool SplitRGBaValue(int Val, int iRed, int iGreen, int iBlue, int iAlpha);
global func int Sqrt(int iValue);
global func bool StartScriptProfiler(id idDefScript);
global func bool StopScriptProfiler();
global func bool Stuck();
global func int Tan(int iAngle, int iRadius, int iPrec);
global func object this();
global func int ToggleBit(int iOldVal, int iBitNumber);
global func bool TrainPhysical(string szPhysical, int iTrainBy, int iMaxTrain);
global func bool UnselectCrew(int iPlr);
global func & VarN(string szName);
global func int VerticesStuck(object pObj);
global func string WildcardMatch(string szStr, string szWildcard);
global func any _inherited();
global func any AsyncRandom();
global func any SetKiller();
global func any SetName();
global func any CreatePropList();
global func any ClearLastPlrCom();
global func any GetPlrControlName();
global func any SurrenderPlayer();
global func any SetLeaguePerformance();
global func any GetViewCursor();
global func any SetViewCursor();
global func any GetTexture();
global func any BlastObject();
global func any BlastFree();
global func any DrawVolcanoBranch();
global func any SetMenuDecoration();
global func any SetMenuTextProgress();
global func any GetLeague();
global func any TestMessageBoard();
global func any CallMessageBoard();
global func any AbortMessageBoard();
global func any OnMessageBoardAnswer();
global func any ActivateGameGoalMenu();
global func any CastBackParticles();
global func any GetMatAdjust();
global func any GetObjectLayer();
global func any SetObjectLayer();
global func any DrawMatChunks();
global func any SetTextureIndex();
global func any RemoveUnusedTexMapEntries();
global func any SetObjDrawTransform2();
global func any LoadScenarioSection();
global func any SetObjectStatus();
global func any GetObjectStatus();
global func any AdjustWalkRotation();
global func any FxFireStart();
global func any FxFireTimer();
global func any FxFireStop();
global func any FxFireInfo();
global func any ModulateColor();
global func any SetPreSend();
global func any GetTeamConfig();
global func any InitScenarioPlayer();
global func any GetScoreboardString();
global func any GetScoreboardData();
global func any AddEvaluationData();
global func any HideSettlementScoreInEvaluation();
global func any FatalError();
global func any PlayVideo();
global func any StartCallTrace();
global func any PauseGame();
global func any ExecuteCommand();
global func any LocateFunc();
global func any SetNextMission();
global func any IncinerateLandscape();
global func any Equal(par1, par2, par3, par4, par5, par6, par7, par8, par9, par10);
global func bool PlayerObjectCommand(int par1, string par2, par3, par4, int par5, par6, par7, int par8, par9, par10);
global func bool PathFree2(par1, par2, int par3, int par4, par5, par6, par7, par8, par9, par10);
global func any GameCallEx(string par1, par2, par3, par4, par5, par6, par7, par8, par9, par10);
global func bool AddMessage(string par1, par2, par3, par4, par5, par6, par7, par8, par9, par10);
global func bool DebugLog(string par1, par2, par3, par4, par5, par6, par7, par8, par9, par10);
global func int GetIndexOf(par1, array par2, par3, par4, par5, par6, par7, par8, par9, par10);
