static const C4D_All;
static const C4D_StaticBack;
static const C4D_Structure;
static const C4D_Vehicle;
static const C4D_Living;
static const C4D_Object;
static const C4D_Goal;
static const C4D_Environment;
static const C4D_Knowledge;
static const C4D_Magic;
static const C4D_Rule;
static const C4D_Background;
static const C4D_SelectNest;
static const C4D_Parallax;
static const C4D_MouseSelect;
static const C4D_Foreground;
static const C4D_MouseIgnore;
static const C4D_IgnoreFoW;
static const C4D_GrabGet;
static const C4D_GrabPut;
static const C4D_LinePower;
static const C4D_LineSource;
static const C4D_LineDrain;
static const C4D_LineLightning;
static const C4D_LineVolcano;
static const C4D_LineRope;
static const C4D_LineColored;
static const C4D_LineVertex;
static const C4D_PowerInput;
static const C4D_PowerOutput;
static const C4D_LiquidInput;
static const C4D_LiquidOutput;
static const C4D_PowerGenerator;
static const C4D_PowerConsumer;
static const C4D_LiquidPump;
static const C4D_ConnectRope;
static const C4D_EnergyHolder;
static const APS_Color;
static const APS_Graphics;
static const APS_Name;
static const APS_Overlay;
static const C4V_Any;
static const C4V_Int;
static const C4V_Bool;
static const C4V_C4ID;
static const C4V_C4Object;
static const C4V_String;
static const C4V_Array;
static const COMD_None;
static const COMD_Stop;
static const COMD_Up;
static const COMD_UpRight;
static const COMD_Right;
static const COMD_DownRight;
static const COMD_Down;
static const COMD_DownLeft;
static const COMD_Left;
static const COMD_UpLeft;
static const DIR_Left;
static const DIR_Right;
static const CON_CursorLeft;
static const CON_CursorToggle;
static const CON_CursorRight;
static const CON_Throw;
static const CON_Up;
static const CON_Dig;
static const CON_Left;
static const CON_Down;
static const CON_Right;
static const CON_Menu;
static const CON_Special;
static const CON_Special2;
static const OCF_Construct;
static const OCF_Grab;
static const OCF_Collectible;
static const OCF_OnFire;
static const OCF_HitSpeed1;
static const OCF_Fullcon;
static const OCF_Inflammable;
static const OCF_Chop;
static const OCF_Rotate;
static const OCF_Exclusive;
static const OCF_Entrance;
static const OCF_HitSpeed2;
static const OCF_HitSpeed3;
static const OCF_Collection;
static const OCF_Living;
static const OCF_HitSpeed4;
static const OCF_FightReady;
static const OCF_LineConstruct;
static const OCF_Prey;
static const OCF_AttractLightning;
static const OCF_NotContained;
static const OCF_CrewMember;
static const OCF_Edible;
static const OCF_InLiquid;
static const OCF_InSolid;
static const OCF_InFree;
static const OCF_Available;
static const OCF_PowerConsumer;
static const OCF_PowerSupply;
static const OCF_Container;
static const OCF_Alive;
static const VIS_All;
static const VIS_None;
static const VIS_Owner;
static const VIS_Allies;
static const VIS_Enemies;
static const VIS_Local;
static const VIS_God;
static const VIS_LayerToggle;
static const VIS_OverlayOnly;
static const C4X_Ver1;
static const C4X_Ver2;
static const C4X_Ver3;
static const C4X_Ver4;
static const C4X_VerBuild;
static const SkyPar_Keep;
static const C4MN_Style_Normal;
static const C4MN_Style_Context;
static const C4MN_Style_Info;
static const C4MN_Style_Dialog;
static const C4MN_Style_EqualItemHeight;
static const C4MN_Extra_None;
static const C4MN_Extra_Components;
static const C4MN_Extra_Value;
static const C4MN_Extra_MagicValue;
static const C4MN_Extra_Info;
static const C4MN_Extra_ComponentsMagic;
static const C4MN_Extra_LiveMagicValue;
static const C4MN_Extra_ComponentsLiveMagic;
static const C4MN_Add_ImgRank;
static const C4MN_Add_ImgIndexed;
static const C4MN_Add_ImgObjRank;
static const C4MN_Add_ImgObject;
static const C4MN_Add_ImgTextSpec;
static const C4MN_Add_ImgColor;
static const C4MN_Add_PassValue;
static const C4MN_Add_ForceCount;
static const C4MN_Add_ForceNoDesc;
static const FX_OK;
static const FX_Effect_Deny;
static const FX_Effect_Annul;
static const FX_Effect_AnnulDoCalls;
static const FX_Execute_Kill;
static const FX_Stop_Deny;
static const FX_Start_Deny;
static const FX_Call_Normal;
static const FX_Call_Temp;
static const FX_Call_TempAddForRemoval;
static const FX_Call_RemoveClear;
static const FX_Call_RemoveDeath;
static const CSPF_Invisible;
static const CSPF_NoEliminationCheck;
static const CSPF_NoScenarioInit;
static const CSPF_FixedAttributes;
static const C4PT_Script;
static const C4PT_User;
static const MSG_Multiple;
static const MSG_Bottom;
static const MSG_NoLinebreak;
static const TEAMID_New;
static const C4SECT_KeepEffects;
static const C4SECT_SaveObjects;
static const C4SECT_SaveLandscape;
static const C4CMD_Enter_PushTarget;
static const C4CMD_MoveTo_PushTarget;
static const C4CMD_MoveTo_NoPosAdjust;
static const C4CMD_SilentSub;
static const C4CMD_Sub;
static const C4CMD_SilentBase;
static const C4CMD_Base;
static const PHYS_StackTemporary;
static const PHYS_Temporary;
static const PHYS_Permanent;
static const PHYS_Current;
static const C4SO_Func;
static const C4SO_Value;
static const C4SO_Mass;
static const C4SO_Speed;
static const C4SO_Random;
static const C4SO_Distance;
static const C4SO_Multiple;
static const C4SO_Reverse;
static const C4FO_Layer;
static const C4FO_Func;
static const C4FO_Owner;
static const C4FO_AnyContainer;
static const C4FO_Container;
static const C4FO_ActionTarget;
static const C4FO_Action;
static const C4FO_Category;
static const C4FO_OCF;
static const C4FO_ID;
static const C4FO_Distance;
static const C4FO_OnLine;
static const C4FO_AtRect;
static const C4FO_AtPoint;
static const C4FO_InRect;
static const C4FO_Exclude;
static const C4FO_Or;
static const C4FO_And;
static const C4FO_Not;
static const C4MSGCMDR_Identifier;
static const C4MSGCMDR_Plain;
static const C4MSGCMDR_Escaped;
static const C4OS_INACTIVE;
static const C4OS_NORMAL;
static const C4OS_DELETED;
static const TEAM_TeamColors;
static const TEAM_AutoGenerateTeams;
static const TEAM_AllowTeamSwitch;
static const TEAM_Dist;
static const TEAM_AllowHostilityChange;
static const TEAM_Active;
static const TEAM_Custom;
static const SBRD_Caption;
static const C4M_Background;
static const C4M_Liquid;
static const C4M_SemiSolid;
static const C4M_Solid;
static const C4M_Vehicle;
static const VTX_SetPermanentUpd;
static const VTX_SetPermanent;
static const VTX_Friction;
static const VTX_CNAT;
static const VTX_Y;
static const VTX_X;
static const GFX_BLIT_Parent;
static const GFX_BLIT_Custom;
static const GFX_BLIT_ClrSfc_Mod2;
static const GFX_BLIT_ClrSfc_OwnClr;
static const GFX_BLIT_Mod2;
static const GFX_BLIT_Additive;
static const GFXOV_UI;
static const GFXOV_Misc;
static const GFXOV_ProcessTarget;
static const GFXOV_Tools;
static const GFXOV_Clothing;
static const GFX_Overlay;
static const GFXOV_MODE_ExtraGraphics;
static const GFXOV_MODE_Object;
static const GFXOV_MODE_IngamePicture;
static const GFXOV_MODE_Picture;
static const GFXOV_MODE_Action;
static const GFXOV_MODE_Base;
static const GFXOV_MODE_None;
static const FX_Call_EngGetPunched;
static const FX_Call_EngStruct;
static const FX_Call_EngCorrosion;
static const FX_Call_EngAsphyxiation;
static const FX_Call_EngBaseRefresh;
static const FX_Call_EngFire;
static const FX_Call_EngObjHit;
static const FX_Call_EngBlast;
static const FX_Call_EngScript;
static const FX_Call_Energy;
static const FX_Call_DmgChop;
static const FX_Call_DmgFire;
static const FX_Call_DmgBlast;
static const FX_Call_DmgScript;
static const CNAT_None;
static const CNAT_Left;
static const CNAT_Right;
static const CNAT_Top;
static const CNAT_Bottom;
static const CNAT_Center;
static const CNAT_MultiAttach;
static const CNAT_NoCollision;
static const NO_OWNER;
static const C4D_SelectHomebase;
static const C4D_SelectVehicle;
static const C4D_SelectKnowledge;
static const C4D_SelectBuilding;
static const C4D_SelectAnimal;
static const C4D_SelectMaterial;
static const C4D_TradeLiving;
static const C4D_SelectInEarth;
static const C4D_SelectVegetation;

global func bool DebugLog(string szMessage, ...);
global func int Abs(int iValue);
global func int Angle(int iX1, int iY1, int iX2, int iY2, int iPrec);
global func int ArcCos(int iVal, int iRadius);
global func int ArcSin(int iVal, int iRadius);
global func int BitAnd(int iVal1, int iVal2);
global func int BoundBy(int iVal, int iRange1, int iRange2);
global func int Cos(int iAngle, int iRadius, int iPrec);
global func int Distance(int iX1, int iY1, int iX2, int iY2);
global func int Div(int iVal1, int iVal2);
global func bool Inside(int iVal, int iRange1, int iRange2);
global func int Max(int iVal1, int iVal2);
global func int Min(int iVal1, int iVal2);
global func int Mod(int iVal1, int iVal2);
global func int Mul(int iVal1, int iVal2);
global func int Pow(int iVal1, int iVal2);
global func int Random(int iMaxVal);
global func int Sin(int iAngle, int iRadius, int iPrec);
global func int Sqrt(int iValue);
global func int Sub(int iVal1, int iVal2, int iVal3, int iVal4);
global func int Sum(int iVal1, int iVal2, int iVal3, int iVal4);
global func int AddEffect(string szEffectName, object pTarget, int iPrio, int iTimerIntervall, object pCmdTarget, id  idCmdTarget, var1, var2, var3, var4);
global func bool ChangeEffect(string szEffectName, object pTarget, int iIndex, string szNewEffectName, int iNewTimer);
global func int CheckEffect(string szEffectName, object pTarget, int iPrio, int iTimerIntervall, var1, var2, var3, var4);
global func any EffectCall(object pTarget, int iNumber, string szCommand, ...);
global func & EffectVar(int iVarIndex, object pTarget, int iNumber);
global func any GetEffect(string szEffectName, object pTarget, int iIndex, int iQueryVal, int iMaxPriority);
global func int GetEffectCount(string szMask, object pTarget, int iMaxPriority);
global func bool RemoveEffect(string szEffectName, object pTarget, int iIndex, bool fDoNoCalls, int iNewTimer);
global func bool Sound(string szSound, bool fGlobal, object pObj, int iVolume, int iPlayer, int iLoopCount);
global func bool SoundLevel(string szSound, int iVolume, object pObj);
global func object EditCursor();
global func bool ReloadDef(id idDef);
global func bool ReloadParticle(string szParticle);
global func bool StartScriptProfiler(id idDefScript);
global func bool StopScriptProfiler();
global func any GetActMapVal(string strEntry, string strAction, id idDef, int iEntryNr);
global func any GetDefCoreVal(string strEntry, string strSection, id idDef, int iEntryNr);
global func any GetMaterialVal(string strEntry, string strSection, int iMaterial, int iEntryNr);
global func any GetObjectInfoCoreVal(string strEntry, string strSection, object pObj, int iEntryNr);
global func any GetObjectVal(string strEntry, string strSection, object pObj, int iEntryNr);
global func any GetPlayerInfoCoreVal(string strEntry, string strSection, id iPlayer, int iEntryNr);
global func any GetPlayerVal(string strEntry, string strSection, int iPlayer, int iEntryNr);
global func any GetScenarioVal(string strEntry, string strSection, int iEntryNr);
global func int FrameCounter();
global func bool GameOver();
global func int GetGravity();
global func bool IsNetwork();
global func bool IsNewgfx();
global func bool ResetGamma(int iRampIndex);
global func bool SetGameSpeed(int iGameSpeed);
global func bool SetGamma(int dwClr1, int dwClr2, int dwClr3, int iRampIndex);
global func int SetGravity(int iGravity);
global func int GetSkyAdjust(bool fBackColor);
global func int GetSkyColor(int iIndex, int iRGB);
global func bool SetSkyAdjust(int dwClrMod, int dwBackClr);
global func bool SetSkyColor(int iIndex, int iRed, int iGreen, int iBlue);
global func bool SetSkyFade(int iFromRed, int iFromGreen, int iFromBlue, int iToRed, int iToGreen, int iToBlue);
global func bool SetSkyParallax(int iMode, int iParX, int iParY, int iXDir, int iYDir, int iX, int iY);
global func int SkyPar_Keep();
global func int AddMsgBoardCmd(string strCommand, string strScript);
global func bool DoScoreboardShow(int iChange, int iForPlr);
global func int ScoreboardCol(id idDef);
global func bool SetScoreboardData(int iRowID, int iColID, string sText, int iData);
global func bool SortScoreboard(int iColID, bool fReverse);
global func int ExtractLiquid(int iX, int iY);
global func int ExtractMaterialAmount(int iX, int iY, int iMat, int iAmount);
global func bool GBackLiquid(int iX, int iY);
global func bool GBackSemiSolid(int iX, int iY);
global func bool GBackSky(int iX, int iY);
global func bool GBackSolid(int iX, int iY);
global func int GetMaterial(int iX, int iY);
global func int GetMaterialColor(int iMat, int iNumber, int iChannel);
global func int GetMaterialCount(int iMaterial);
global func bool InsertMaterial(int iMat, int iX, int iY, int iXDir, int iYDir);
global func int Material(string szMaterialName);
global func string MaterialName(int iMat);
global func bool SetMaterialColor(int iMat, int iR1, int iG1, int iB1, int iR2, int iG2, int iB2, int iR3, int iG3, int iB3);
global func int CastPXS(string szMaterial, int iAmount, int iLevel, int iX, int iY);
global func int DigFree(int iX, int iY, int iRadius);
global func int DigFreeRect(int iX, int iY, int iWdt, int iHgt);
global func bool DrawDefMap(int iX, int iY, int iWdt, int iHgt, string szMapDef);
global func bool DrawMap(int iX, int iY, int iWdt, int iHgt, string szMap);
global func bool DrawMaterialQuad(string szMaterialTexture, int iX1, int iY1, int iX2, int iY2, int iX3, int iY3, int iX4, int iY4, bool sub);
global func bool FindConstructionSite(id idDef, int iVarNumX, int iVarNumY);
global func bool FreeRect(int iX, int iY, int iWdt, int iHgt, int iFreeDensity);
global func int GetPathLength(int iFromX, int iFromY, int iToX, int iToY);
global func bool InLiquid(object pObj);
global func int LandscapeHeight();
global func int LandscapeWidth();
global func bool PathFree(int iX1, int iY1, int iX2, int iY2);
global func bool SetClimate(int iClimate);
global func bool SetLandscapePixel(int iX, int iY, int dwValue);
global func bool SetMatAdjust(int dwClrMod);
global func bool ShakeFree(int iX, int iY, int iRadius);
global func int And(int fCon1, int fCon2);
global func bool Equal(int iVal1, int iVal2);
global func bool GreaterThan(int iVal1, int iVal2);
global func bool LessThan(int iValue1, int iValue1);
global func bool Not(bool Value);
global func int Or(int fCon1, int fCon2, int fCon3, int fCon4, int fCon5);
global func int Music(string szSongName, bool fLoop);
global func int MusicLevel(int iLevel);
global func int SetPlayList(string szPlayList);
global func bool CustomMessage(string message, object obj, int plr, int offset_x, int offset_y, int color, id deco, string portrait, int flags);
global func bool Log(string szMessage, ...);
global func bool Message(string strMessage, object pObj, ...);
global func bool PlayerMessage(int iPlr, string szMessage, object pObj, ...);
global func bool PlrMessage(string szMessage, int iPlr, ...);
global func bool ActIdle(object pObj);
global func int GetActTime(object pObj);
global func string GetAction(object pObj);
global func object GetActionTarget(int iTargetIndex, object pObj);
global func int GetDir(object pObj);
global func int GetPhase(object pObj);
global func string GetProcedure(object pObj);
global func bool ObjectSetAction(object pObj, string szAction, object pTarget1, object pTarget2, bool fDirect);
global func bool SetAction(string szAction, object pTarget1, object pTarget2);
global func bool SetActionData(int iData, object pObj);
global func bool SetActionTargets(object pTarget1, object pTarget2, object pObj);
global func bool SetBridgeActionData(int iBridgeLength, bool fMoveClonk, bool fWall, int iBridgeMaterial, object pObj);
global func int SetDir(int iDir, object pObj);
global func bool SetPhase(int iPhase, object pObj);
global func bool Fling(object pObj, int iXDir, int iYDir);
global func int GetComDir(object pObj);
global func int GetR(object pObj);
global func int GetRDir(object pObj, int iPrecision);
global func int GetXDir(object pObj, int iPrecision);
global func int GetYDir(object pObj, int iPrecision);
global func bool Jump(object pObj);
global func int SetComDir(int iComDir, object pObj);
global func bool SetR(int iR, object pObj);
global func bool SetRDir(int iRDir, object pObj, int iPrecision);
global func bool SetXDir(int iXDir, object pObj, int iPrecision);
global func bool SetYDir(int iYDir, object pObj, int iPrecision);
global func bool SimFlight(int & iX, int & iY, int & iXDir, int & iYDir, int iMinDensity, int iMaxDensity, int iIteration, int iPrecision);
global func bool AddCommand(object pObj, string szCommand, object pTarget, int iX, int iY, object pTarget2, int iInterval, Data, int iRetries, int iBaseMode);
global func bool AppendCommand(object pObj, string szCommand, object pTarget, int iX, int iY, object pTarget2, int iInterval, Data, int iRetries, int iBaseMode);
global func bool FinishCommand(object pObj, bool fSuccess, int iCommandNum);
global func any GetCommand(object pObj, int iElement, int iCommandNum);
global func bool SetCommand(object pObj, string szCommand, object pTarget, int iX, int iY, object pTarget2, Data, int iRetries);
global func int GetClrModulation(object pObj, int iOverlayID);
global func int GetColor(object pObj);
global func int GetColorDw(object pObj);
global func int GetObjectBlitMode(object pObj, int iOverlayID);
global func any GetPortrait(object pObj, bool fGetID, bool fGetPermanent);
global func int GetUnusedOverlayID(int iBaseIndex, object pObj);
global func bool SetClrModulation(int dwClr, object pObj, int iOverlayID);
global func bool SetColor(int iColor, object pObj);
global func bool SetColorDw(int dwNewColor, object pObj);
global func bool SetGraphics(string szGfxName, object pObj, id idSrcDef, int iOverlay, int iOverlayMode, string szAction, int dwBlitMode, object pOvelayObject);
global func bool SetObjDrawTransform(int iWidth, int iXSkew, int iXAdjust, int iYSkew, int iHeight, int iYAdjust, object pObj, int iOverlayID);
global func int SetObjectBlitMode(int dwNewBlitMod, object pObj, int iOverlayID);
global func bool SetPicture(int iX, int iY, int iWdt, int iHgt, object pObj);
global func bool SetPortrait(string szPortrait, object pTarget, id idSrcDef, bool fPermanent, bool fCopyGfx);
global func object Buy(id idBuyObj, int iForPlr, int iPayPlr, object pToBase, bool fShowErrors);
global func int CastObjects(id  id, int  iNumber, int  iLevel, int  iX, int  iY);
global func object ComposeContents(id id, object pObj);
global func object CreateConstruction(id id, int iXOffset, int iYOffset, int iOwner, int iCompletion, bool fTerrain, bool fCheckSite);
global func object CreateContents(id id, object pObj, int iCount);
global func object CreateObject(id id, int iXOffset, int iYOffset, int iOwner);
global func bool Explode(int iLevel, object pObj, id idEffect, string szParticle);
global func bool RemoveObject(object pObj, bool fEjectContents);
global func bool Sell(int iPlr, object pObj);
global func bool Split2Components(object pObj);
global func bool Collect(object pItem, object pTarget);
global func object Contained(object pObj);
global func object Contents(int iIndex, object pObj);
global func int ContentsCount(id id, object pObj);
global func bool GrabContents(object pObj);
global func object ScrollContents(object pObj);
global func bool ShiftContents(object pObj, bool fShiftBack, id idTarget, bool fDoCalls);
global func int GetCategory(object pObj, id idDef);
global func bool SetCategory(int iCategory, object pObj);
global func bool ComponentAll(object pObj, id idComponents);
global func int GetComponent(id idComponent, int iIndex, object pObj, id idDef);
global func bool SetComponent(id idComponent, int iCount, object pObj);
global func bool DeathAnnounce();
global func bool DoBreath(int iChange, object pObj);
global func bool GetAlive(object pObj);
global func int GetBreath(object pObj);
global func bool Kill(object pObj, bool fForced);
global func bool Punch(object pObj, int iX);
global func int SetAlive(bool fAlive, object pObj);
global func bool CrewMember(id id);
global func bool DoCrewExp(int iChange, object pObj);
global func object GetCaptain(int iPlayer);
global func int GetController(object pObj);
global func object GetCrew(int iPlayer, int iIndex);
global func int GetCrewCount(int iPlayer);
global func bool GetCrewEnabled(object pObj);
global func object GetCursor(int iPlayer, int iIndex);
global func object GetHiRank(int iPlayer);
global func bool GrabObjectInfo(object pFrom, object pTo);
global func bool MakeCrewMember(object pObj, int iPlayer);
global func bool SetCrewEnabled(bool fEnabled, object pObj);
global func bool SetCrewStatus(int iPlr, bool fInCrew, object pCrew);
global func bool UnselectCrew(int iPlr);
global func int AddMenuItem(string szCaption, string szCommand, id idItem, object pMenuObject, int iCount, Parameter, string szInfoCaption, int iExtra, XPar1, XPar2);
global func int ClearMenuItems(object pMenuObject);
global func bool CloseMenu(object pObj);
global func int CreateMenu(id idSymbol, object pMenuObject, object pCommandObject, int iExtra, string szCaption, int iExtraData, int iStyle, bool fPermanent, id idMenuID);
global func id GetMenu(object pObj);
global func int GetMenuSelection(object pObj);
global func bool SelectMenuItem(int iItem, object pMenuObj);
global func bool SetMenuSize(int iCols, int iRows, object pMenuObj);
global func bool ShowInfo(object pObject);
global func int GetOCF(object pObj);
global func bool Enter(object pTarget, object pObj);
global func bool Exit(object pObj, int iX, int iY, int iR, int iXDir, int iYDir, int iRDir);
global func int GetX(object pObj);
global func int GetY(object pObj);
global func bool Resort(object pObj);
global func bool ResortObject(string szResortFunc, object pResortObj);
global func bool ResortObjects(string szResortFunc, int iCategory);
global func bool SetObjectOrder(object pObjBeforeOrAfter, object pSortObj, bool fAfter);
global func int SetPosition(int iX, int iY, object pObj, bool fCheckBounds);
global func int GetVisibility(object pObj);
global func bool SetVisibility(int dwVisibility, object pObj);
global func bool ChangeDef(id idNewDef, object pObj);
global func bool CheckEnergyNeedChain(object pObj);
global func bool DoCon(int iChange, object pObj);
global func bool DoDamage(int iChange, object pTarget);
global func bool DoEnergy(int iChange, object pObj, bool fExakt, int iEngType, int iCausedBy);
global func bool DoMagicEnergy(int iChange, object pObj, bool fAllowPartial);
global func bool EnergyCheck(int iEnergy, object pObj);
global func bool Extinguish(object pObj);
global func bool FightWith(object pTarget, object pFighter);
global func int GetCon(object pObj);
global func int GetContact(object pObject, int iVertex, int dwCNAT);
global func int GetDamage(object pObj);
global func int GetDefBottom(object pObj);
global func string GetDesc(object pObj, id idDef);
global func int GetKiller(object pObj);
global func int GetMass(object pObj, id idDef);
global func string GetNeededMatStr(object pObj);
global func int GetOwner(object pObj);
global func int GetPhysical(string szPhysical, int iMode, object pObj, id idDef);
global func int GetValue(object pObj, id idDef, object pBase, int iForPlayer);
global func bool OnFire(object pObj);
global func bool ResetPhysical(object pObj, string sPhys);
global func bool SetContactDensity(int iDensity, object pObj);
global func bool SetController(int iNewController, object pObj);
global func bool SetMass(int iNewMass, object pObj);
global func bool SetName(string szNewName, object pObj, id idDef, bool fSetInInfo, bool fMakeValidIfExists);
global func bool SetOwner(int iNewOwner, object pObj);
global func bool SetPhysical(string szPhysical, int iValue, int iMode, object pObj);
global func bool SetSolidMask(int iX, int iY, int iWdt, int iHgt, int iTx, int iTx, object pObj);
global func bool SetTransferZone(int iX, int iY, int iWdt, int iHgt, object pObj);
global func bool Stuck(object pObject);
global func bool TrainPhysical(string szPhysical, int iTrainBy, int iMaxTrain, object pObj);
global func int Value(id idDef);
global func int AnyContainer();
global func object FindBase(int iPlr, int iIndex);
global func object FindContents(id idType, object pObj);
global func object FindObject(id idDef, int iX, int iY, int iWdt, int iHgt, int dwOCF, string szAction, object pActionTarget, pContainer, object pFindNext);
global func object FindObject2(array Criteria, ...);
global func object FindObjectOwner(id idDef, int iOwner, int iX, int iY, int iWdt, int iHgt, int dwOCF, string szAction, object pActionTarget, object pFindNext);
global func array FindObjects(array Criteria, ...);
global func object FindOtherContents(id idType, object pObj);
global func int NoContainer();
global func int ObjectCount(id idDef, int iX, int iY, int iWdt, int iHgt, int dwOCF, string szAction, object pActionTarget, pContainer, int iOwner);
global func int ObjectCount2(array Criteria, ...);
global func int AddVertex(int iX, int iY, object pObj);
global func int GetVertex(int iIndex, bool fY, object pObj);
global func int GetVertexNum(object pObj);
global func int RemoveVertex(int iX, object pObj);
global func int SetVertex(int iIndex, int iValueToSet, int iValue, object pObj, int iSetCustomPermanent);
global func id GetDefinition(int iIndex, int dwCategory);
global func int GetEnergy(object pObj);
global func bool GetEntrance(object pObj);
global func id GetID(object pObj);
global func int GetMagicEnergy(object pObj);
global func string GetName(object pObj, id idDef);
global func int GetRank(object pObj);
global func bool Incinerate(object pObj);
global func object Object(int iObj);
global func int ObjectDistance(object pObj2, object pObj);
global func int ObjectNumber(object pObj);
global func int SetEntrance(int iStatus);
global func bool SetShape(int iX, int iY, int iWdt, int iHgt, object pObj);
global func bool ShakeObjects(int iX, int iY, int iRadius);
global func object this();
global func bool CastParticles(string szName, int iAmount, int iLevel, int iX, int iY, int a0, int a1, int b0, int b1, object pObj);
global func bool ClearParticles(string szName);
global func bool CreateParticle(string szName, int iX, int iY, int iXDir, int iYDir, int a, int b, object pObj, bool fBehind);
global func bool PushParticles(string szName, int iAX, int iAY);
global func any Call(string szFunction, ...);
global func any DefinitionCall(id idDef, string szFunction, ...);
global func any GameCall(string szFunction, ...);
global func any ObjectCall(object pObj, string szFunction, ...);
global func any PrivateCall(object pObj, string szFunction, ...);
global func any ProtectedCall(object pObj, string szFunction, ...);
global func id C4Id(string szID);
global func array CreateArray(int Length);
global func string Format(string szStr, ...);
global func int GetChar(string szText, int iIndex);
global func int GetLength(szText);
global func bool SEqual(string szStr1, string szStr2);
global func int SetLength(array aResize, int iSize);
global func bool WildcardMatch(string szStr, string szWildcard);
global func any Par(int iIndex);
global func int ScriptCounter();
global func bool ScriptGo(bool fStart);
global func any eval(string strScript);
global func bool goto(int iCounter);
global func any inherited();
global func object GetPlrView(int iPlr);
global func int GetPlrViewMode(int iPlr);
global func int SetFilmView(int iToPlr);
global func bool SetFoW(bool fEnabled, int iPlayer);
global func bool SetPlrView(int iPlr, object pObj);
global func bool SetPlrViewRange(int iRange, object pObj);
global func bool SetViewOffset(int iPlayer, int iX, int iX);
global func bool CreateScriptPlayer(string szName, int dwClr, int idTeam, int dwFlags, id idExtraData);
global func bool DoHomebaseMaterial(int iPlr, id idID, int iChange);
global func bool DoHomebaseProduction(int iPlr, id idID, int iChange);
global func bool DoScore(int iPlr, int iChange);
global func bool EliminatePlayer(int iPlr);
global func int GetBase(object pObj);
global func any GetCrewExtraData(object pCrew, string strDataName);
global func int GetHomebaseMaterial(int iPlr, id id, int iIndex, int dwCategory);
global func int GetHomebaseProduction(int iPlr, id id, int iIndex, int dwCategory);
global func int GetPlayerByIndex(int iIndex, int ePlayerType);
global func int GetPlayerCount(int ePlayerType);
global func int GetPlayerID(int iPlayerNumber);
global func string GetPlayerName(int iPlayer);
global func int GetPlayerTeam(int iPlr);
global func int GetPlayerType(int iPlayer);
global func int GetPlrColorDw(int iPlr);
global func bool GetPlrDownDouble(int iPlr);
global func any GetPlrExtraData(int iPlr, string strDataName);
global func int GetPlrKnowledge(int iPlr, id id, int iIndex, int dwCategory);
global func int GetPlrMagic(int iPlr, id id, int iIndex);
global func int GetScore(int iPlayer);
global func int GetSelectCount(int iPlayer);
global func string GetTaggedPlayerName(int iPlayer);
global func int GetWealth(int iOwner);
global func bool Hostile(int iPlr1, int iPlr2, bool fCheckOneWayOnly);
global func bool SelectCrew(int iPlr, object pObj, bool fSelect);
global func any SetCrewExtraData(object pCrew, string strDataName, Data);
global func bool SetCursor(int iPlr, object pObj, bool fNoSelectMark, bool fNoSelectArrow);
global func bool SetHostility(int iPlr1, int iPlr2, bool fHostile, bool fSilent, bool fNoCalls);
global func bool SetMaxPlayer(int iNewCount);
global func int SetPlayerTeam(int iPlr, int idNewTeam, bool fDoNoCalls);
global func any SetPlrExtraData(int iPlr, string strDataName, Data);
global func int SetPlrKnowledge(int iPlr, id idDef, bool fRemove);
global func int SetPlrMagic(int iPlr, id id, bool Remove);
global func bool SetPlrShowCommand(int iPlr, int iCom);
global func bool SetPlrShowControl(int iPlr, string szDefString);
global func bool SetPlrShowControlPos(int iPlr, int iPos);
global func bool SetWealth(int iPlr, int iValue);
global func bool GainMissionAccess(string szPassword);
global func bool GetMissionAccess(string strMissionAccess);
global func int GetSystemTime(int iWhat);
global func int GetTime();
global func int GetTeamByIndex(int iIndex);
global func int GetTeamColor(int iTeam);
global func int GetTeamCount();
global func string GetTeamName(int iTeam);
global func bool Bubble(int iX, int iY);
global func bool Smoke(int iX, int iY, int iLevel);
global func int GetClimate();
global func int GetSeason();
global func int GetTemperature();
global func int GetWind(int iX, int iY, bool fGlobal);
global func bool LaunchLightning(int iX, int iY, int iXAdvance, int iXRange, int iYAdvance, int iYRange, bool fDoGamma);
global func bool SetSeason(int iSeason);
global func bool SetTemperature(int iTemperature);
global func bool SetWind(int iWind);
global func bool LaunchEarthquake(int iX, int iY);
global func object PlaceAnimal(id id);
global func object PlaceVegetation(id id, int iX, int iY, int iWdt, int iHgt, int iGrowth);
global func int AssignVar(int iVarIndex, int iValue);
global func int Dec(int & Var);
global func int DecVar(int iVarNum);
global func int GetType(Value);
global func & Global(int iVarIndex);
global func & GlobalN(string szText);
global func int Inc(int & Var);
global func int IncVar(int iVarNum);
global func bool IsRef(Value);
global func & Local(int iVarIndex, object pObj);
global func & LocalN(string szName, object pObj);
global func int SetGlobal(int iVarIndex, Value);
global func & SetLocal(int iVarIndex, Value, object pObj);
global func & SetVar(int iVarIndex, Value);
global func & Var(int iIndex);
global func & VarN(string szName);
global func int AbortMessageBoard();
global func int ActivateGameGoalMenu();
global func int AddEvaluationData();
global func int AddMessage();
global func int AdjustWalkRotation();
global func int AsyncRandom();
global func int BlastFree();
global func int BlastObject();
global func int CallMessageBoard();
global func int CastBackParticles();
global func int ClearLastPlrCom();
global func int DrawMatChunks();
global func int DrawModLandscape();
global func int DrawVolcanoBranch();
global func int ExecuteCommand();
global func int FatalError(string szMessage);
global func int FlameConsumeMaterial();
global func int GameCallEx();
global func int GetIndexOf(iNeedle, array aHaystack);
global func int GetMatAdjust();
global func int GetObjectStatus();
global func int GetScoreboardData();
global func int GetTeamConfig(int iConfigValue);
global func int IncinerateLandscape();
global func int InitScenarioPlayer();
global func int LoadScenarioSection();
global func int LocateFunc();
global func int ModulateColor(int color1, int color2);
global func int OnMessageBoardAnswer();
global func bool PathFree2(int iX1, int iY1, int iX2, int iY2);
global func bool PauseGame(bool toggle);
global func int PlayVideo();
global func int PlayerObjectCommand();
global func int RemoveUnusedTexMapEntries();
global func int Set();
global func bool SetKiller(int iNewKiller, object pObj);
global func bool SetMenuDecoration(id idNewDeco, object pMenuObj);
global func bool SetMenuTextProgress(int iNewProgress, object pMenuObj);
global func bool SetObjDrawTransform2(int iA, int iB, int iC, int iD, id iE, int iF, int iG, int iH, int iI, int iOverlayID);
global func bool SetObjectLayer(object pNewLayer, object pObj);
global func bool SetObjectStatus(int iNewStatus, object pObj, bool fClearPointers);
global func bool SetPreSend(int iToVal, string pNewName);
global func int SetTextureIndex();
global func int SetViewCursor();
global func int StartCallTrace();
global func bool SurrenderPlayer(int iPlr);
global func int TestMessageBoard();
global func string GetLeague(int id);
global func object GetObjectLayer(object pObj);
global func id CastC4ID(par1);
global func int _inherited();
global func int CastInt(par0);
global func string GetPlrControlName(int player, int key);
global func bool SetLeaguePerformance(int par0);
global func object GetViewCursor(int par0);
global func string GetTexture(int par0, int par1);
global func int FxFireStart(object par0, int par1, int par2, int par3, bool par4, object par5);
global func int FxFireTimer(object par0, int par1, int par2);
global func int FxFireStop(object par0, int par1, int par2, bool par3);
global func string FxFireInfo(object par0, int par1);
global func bool OnOwnerRemoved();
global func string GetScoreboardString(int par0, int par1);
global func bool SetNextMission(string par0, string par1, string par2);
global func any CastBool(par0, par1, par2, par3, par4, par5, par6, par7, par8, par9);
global func any CastAny(par0, par1, par2, par3, par4, par5, par6, par7, par8, par9);
